	.align 2
gTilesetTiles_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/petalburg/palettes/15.gbapal"

	.align 2
gTilesetTiles_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rustboro/palettes/15.gbapal"

	.align 2
gTilesetTiles_Dewford::
	.incbin "data/tilesets/secondary/dewford/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Dewford::
	.incbin "data/tilesets/secondary/dewford/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dewford/palettes/15.gbapal"

	.align 2
gTilesetTiles_Slateport::
	.incbin "data/tilesets/secondary/slateport/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Slateport::
	.incbin "data/tilesets/secondary/slateport/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/slateport/palettes/15.gbapal"

	.align 2
gTilesetTiles_Mauville::
	.incbin "data/tilesets/secondary/mauville/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Mauville::
	.incbin "data/tilesets/secondary/mauville/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lavaridge/palettes/15.gbapal"

	.align 2
gTilesetTiles_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fallarbor/palettes/15.gbapal"

	.align 2
gTilesetTiles_Fortree::
	.incbin "data/tilesets/secondary/fortree/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Fortree::
	.incbin "data/tilesets/secondary/fortree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fortree/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lilycove/palettes/15.gbapal"

	.align 2
gTilesetTiles_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep/palettes/15.gbapal"

	.align 2
gTilesetTiles_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/ever_grande/palettes/15.gbapal"

	.align 2
gTilesetTiles_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pacifidlog/palettes/15.gbapal"

	.align 2
gTilesetTiles_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sootopolis/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/palettes/15.gbapal"

	.align 2
gTilesetTiles_InsideBuilding::
	.incbin "data/tilesets/primary/building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideBuilding::
	.incbin "data/tilesets/primary/building/palettes/00.gbapal"
	.incbin "data/tilesets/primary/building/palettes/01.gbapal"
	.incbin "data/tilesets/primary/building/palettes/02.gbapal"
	.incbin "data/tilesets/primary/building/palettes/03.gbapal"
	.incbin "data/tilesets/primary/building/palettes/04.gbapal"
	.incbin "data/tilesets/primary/building/palettes/05.gbapal"
	.incbin "data/tilesets/primary/building/palettes/06.gbapal"
	.incbin "data/tilesets/primary/building/palettes/07.gbapal"
	.incbin "data/tilesets/primary/building/palettes/08.gbapal"
	.incbin "data/tilesets/primary/building/palettes/09.gbapal"
	.incbin "data/tilesets/primary/building/palettes/10.gbapal"
	.incbin "data/tilesets/primary/building/palettes/11.gbapal"
	.incbin "data/tilesets/primary/building/palettes/12.gbapal"
	.incbin "data/tilesets/primary/building/palettes/13.gbapal"
	.incbin "data/tilesets/primary/building/palettes/14.gbapal"
	.incbin "data/tilesets/primary/building/palettes/15.gbapal"

	.align 2
gTilesetTiles_Shop::
	.incbin "data/tilesets/secondary/shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Shop::
	.incbin "data/tilesets/secondary/shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_center/palettes/15.gbapal"

	.align 2
gTilesetTiles_Cave::
	.incbin "data/tilesets/secondary/cave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Cave::
	.incbin "data/tilesets/secondary/cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_school/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_fan_club/palettes/15.gbapal"

	.align 2
gTilesetTiles_Unused1::
	.incbin "data/tilesets/secondary/unused_1/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Unused1::
	.incbin "data/tilesets/secondary/unused_1/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/unused_1/palettes/15.gbapal"

	.align 2
gTilesetTiles_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/meteor_falls/palettes/15.gbapal"

	.align 2
gTilesetTiles_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/oceanic_museum/palettes/15.gbapal"

	.align 2
gTilesetTiles_CableClub::
	.incbin "data/tilesets/secondary/cable_club/tiles.4bpp"

	.align 2
	.incbin "data/tilesets/secondary/cable_club/unknown_tiles.4bpp"

	.align 2
gTilesetPalettes_CableClub::
	.incbin "data/tilesets/secondary/cable_club/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/cable_club/palettes/15.gbapal"

	.align 2
gTilesetTiles_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/seashore_house/palettes/15.gbapal"

	.align 2
gTilesetTiles_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/pokemon_day_care/palettes/15.gbapal"

	.align 2
gTilesetTiles_Facility::
	.incbin "data/tilesets/secondary/facility/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Facility::
	.incbin "data/tilesets/secondary/facility/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/facility/palettes/15.gbapal"

	.align 2
gTilesetTiles_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/bike_shop/palettes/15.gbapal"

	.align 2
gTilesetTiles_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rusturf_tunnel/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/brown_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseBrownCave::
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/brown_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/tree/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseTree::
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/tree/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/shrub/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseShrub::
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/shrub/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/blue_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseBlueCave::
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/blue_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseYellowCave::
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/palettes/15.gbapal"

	.align 2
@ unused compressed copy of tiles
	.incbin "data/tilesets/secondary/secret_base/red_cave/unused_tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SecretBaseRedCave::
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/secret_base/red_cave/palettes/15.gbapal"

	.align 2
gTilesetTiles_SecretBaseBrownCave::
	.incbin "data/tilesets/secondary/secret_base/brown_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseTree::
	.incbin "data/tilesets/secondary/secret_base/tree/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseShrub::
	.incbin "data/tilesets/secondary/secret_base/shrub/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseBlueCave::
	.incbin "data/tilesets/secondary/secret_base/blue_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseYellowCave::
	.incbin "data/tilesets/secondary/secret_base/yellow_cave/tiles.4bpp"

	.align 2
gTilesetTiles_SecretBaseRedCave::
	.incbin "data/tilesets/secondary/secret_base/red_cave/tiles.4bpp"

	.align 2
gTilesetTiles_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/inside_of_truck/palettes/15.gbapal"

	.align 2
gTilesetTiles_Contest::
	.incbin "data/tilesets/secondary/contest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Contest::
	.incbin "data/tilesets/secondary/contest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/contest/palettes/15.gbapal"

	.align 2
gTilesetTiles_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lilycove_museum/palettes/15.gbapal"

	.align 2
gTilesetTiles_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/brendans_mays_house/palettes/15.gbapal"

	.align 2
gTilesetTiles_Lab::
	.incbin "data/tilesets/secondary/lab/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Lab::
	.incbin "data/tilesets/secondary/lab/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lab/palettes/15.gbapal"

	.align 2
gTilesetTiles_Underwater::
	.incbin "data/tilesets/secondary/underwater/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Underwater::
	.incbin "data/tilesets/secondary/underwater/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/underwater/palettes/15.gbapal"

	.align 2
gTilesetTiles_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/generic_building/palettes/15.gbapal"

	.align 2
gTilesetTiles_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville_game_corner/palettes/15.gbapal"

	.align 2
gTilesetTiles_Unused2::
	.incbin "data/tilesets/secondary/unused_2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Unused2::
	.incbin "data/tilesets/secondary/unused_2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/unused_2/palettes/15.gbapal"

	.align 2
gTilesetTiles_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/rustboro_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/dewford_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mauville_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/lavaridge_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/petalburg_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/fortree_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/sootopolis_gym/palettes/15.gbapal"

	.align 2
gTilesetTiles_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trick_house_puzzle/palettes/15.gbapal"

	.align 2
gTilesetTiles_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/inside_ship/palettes/15.gbapal"

	.align 2
gTilesetTiles_SecretBase::
	.incbin "data/tilesets/primary/secret_base/tiles.4bpp"

	.align 2
	.incbin "data/tilesets/primary/secret_base/unknown_tiles.4bpp"

	.align 2
gTilesetPalettes_SecretBase::
	.incbin "data/tilesets/primary/secret_base/palettes/00.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/01.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/02.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/03.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/04.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/05.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/06.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/07.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/08.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/09.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/10.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/11.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/12.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/13.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/14.gbapal"
	.incbin "data/tilesets/primary/secret_base/palettes/15.gbapal"

	.align 2
gTilesetTiles_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/elite_four/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_palace/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_dome/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_factory/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_pike/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_arena/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_pyramid/palettes/15.gbapal"

	.align 2
gTilesetTiles_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mirage_tower/palettes/15.gbapal"

	.align 2
gTilesetTiles_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mossdeep_game_corner/palettes/15.gbapal"

	.align 2
gTilesetTiles_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/island_harbor/palettes/15.gbapal"

	.align 2
gTilesetTiles_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/trainer_hill/palettes/15.gbapal"

	.align 2
gTilesetTiles_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/navel_rock/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/palettes/15.gbapal"

	.align 2
gTilesetTiles_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/battle_tent/palettes/15.gbapal"

	.align 2
gTilesetTiles_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/mystery_events_house/palettes/15.gbapal"

	.align 2
gTilesetPalettes_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/12.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/13.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/14.gbapal"
	.incbin "data/tilesets/secondary/union_room/palettes/15.gbapal"

	.align 2
gTilesetTiles_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoGeneral::
	.incbin "data/tilesets/primary/kantogeneral/palettes/00.gbapal"
	.incbin "data/tilesets/primary/kantogeneral/palettes/01.gbapal"
	.incbin "data/tilesets/primary/kantogeneral/palettes/02.gbapal"
	.incbin "data/tilesets/primary/kantogeneral/palettes/03.gbapal"
	.incbin "data/tilesets/primary/kantogeneral/palettes/04.gbapal"
	.incbin "data/tilesets/primary/kantogeneral/palettes/05.gbapal"
	.incbin "data/tilesets/primary/kantogeneral/palettes/06.gbapal"
	.incbin "data/tilesets/primary/kantogeneral/palettes/07.gbapal"
	.incbin "data/tilesets/primary/kantogeneral/palettes/08.gbapal"
	.incbin "data/tilesets/primary/kantogeneral/palettes/09.gbapal"
	.incbin "data/tilesets/primary/kantogeneral/palettes/10.gbapal"
	.incbin "data/tilesets/primary/kantogeneral/palettes/11.gbapal"
	.incbin "data/tilesets/primary/kantogeneral/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoGeneral::
	.incbin "data/tilesets/primary/kantogeneral/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PalletTown::
	.incbin "data/tilesets/secondary/pallettown/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pallettown/palettes/12.gbapal"

	.align 2
gTilesetTiles_PalletTown::
	.incbin "data/tilesets/secondary/pallettown/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ViridianCity::
	.incbin "data/tilesets/secondary/viridiancity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridiancity/palettes/12.gbapal"

	.align 2
gTilesetTiles_ViridianCity::
	.incbin "data/tilesets/secondary/viridiancity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoBuilding::
	.incbin "data/tilesets/primary/kantobuilding/palettes/00.gbapal"
	.incbin "data/tilesets/primary/kantobuilding/palettes/01.gbapal"
	.incbin "data/tilesets/primary/kantobuilding/palettes/02.gbapal"
	.incbin "data/tilesets/primary/kantobuilding/palettes/03.gbapal"
	.incbin "data/tilesets/primary/kantobuilding/palettes/04.gbapal"
	.incbin "data/tilesets/primary/kantobuilding/palettes/05.gbapal"
	.incbin "data/tilesets/primary/kantobuilding/palettes/06.gbapal"
	.incbin "data/tilesets/primary/kantobuilding/palettes/07.gbapal"
	.incbin "data/tilesets/primary/kantobuilding/palettes/08.gbapal"
	.incbin "data/tilesets/primary/kantobuilding/palettes/09.gbapal"
	.incbin "data/tilesets/primary/kantobuilding/palettes/10.gbapal"
	.incbin "data/tilesets/primary/kantobuilding/palettes/11.gbapal"
	.incbin "data/tilesets/primary/kantobuilding/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoBuilding::
	.incbin "data/tilesets/primary/kantobuilding/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoBuilding1::
	.incbin "data/tilesets/secondary/kantobuilding1/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding1/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding1/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding1/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding1/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding1/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding1/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding1/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding1/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding1/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding1/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding1/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding1/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoBuilding1::
	.incbin "data/tilesets/secondary/kantobuilding1/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoBuilding2::
	.incbin "data/tilesets/secondary/kantobuilding2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding2/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoBuilding2::
	.incbin "data/tilesets/secondary/kantobuilding2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoOaksLab::
	.incbin "data/tilesets/secondary/kantooakslab/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantooakslab/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantooakslab/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantooakslab/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantooakslab/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantooakslab/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantooakslab/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantooakslab/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantooakslab/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantooakslab/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantooakslab/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantooakslab/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantooakslab/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoOaksLab::
	.incbin "data/tilesets/secondary/kantooakslab/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ViridianCityGym::
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridiancitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_ViridianCityGym::
	.incbin "data/tilesets/secondary/viridiancitygym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoBuilding3::
	.incbin "data/tilesets/secondary/kantobuilding3/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding3/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding3/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding3/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding3/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding3/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding3/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding3/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding3/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding3/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding3/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding3/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantobuilding3/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoBuilding3::
	.incbin "data/tilesets/secondary/kantobuilding3/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoPokeMart::
	.incbin "data/tilesets/secondary/kantopokemart/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantopokemart/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantopokemart/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantopokemart/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantopokemart/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantopokemart/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantopokemart/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantopokemart/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantopokemart/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantopokemart/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantopokemart/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantopokemart/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantopokemart/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoPokeMart::
	.incbin "data/tilesets/secondary/kantopokemart/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoPokeCenter::
	.incbin "data/tilesets/secondary/kantopokecenter/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantopokecenter/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantopokecenter/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantopokecenter/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantopokecenter/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantopokecenter/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantopokecenter/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantopokecenter/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantopokecenter/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantopokecenter/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantopokecenter/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantopokecenter/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantopokecenter/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoPokeCenter::
	.incbin "data/tilesets/secondary/kantopokecenter/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PewterCity::
	.incbin "data/tilesets/secondary/pewtercity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewtercity/palettes/12.gbapal"

	.align 2
gTilesetTiles_PewterCity::
	.incbin "data/tilesets/secondary/pewtercity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PewterCityMuseum::
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewtercitymuseum/palettes/12.gbapal"

	.align 2
gTilesetTiles_PewterCityMuseum::
	.incbin "data/tilesets/secondary/pewtercitymuseum/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PewterCityGym::
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pewtercitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_PewterCityGym::
	.incbin "data/tilesets/secondary/pewtercitygym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanCity::
	.incbin "data/tilesets/secondary/ceruleancity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ceruleancity/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeruleanCity::
	.incbin "data/tilesets/secondary/ceruleancity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanCityCrimeHouse::
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeruleanCityCrimeHouse::
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanCityGym::
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeruleanCityGym::
	.incbin "data/tilesets/secondary/ceruleancitygym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanCityBikeShop::
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeruleanCityBikeShop::
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_LavenderTown::
	.incbin "data/tilesets/secondary/lavendertown/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/lavendertown/palettes/12.gbapal"

	.align 2
gTilesetTiles_LavenderTown::
	.incbin "data/tilesets/secondary/lavendertown/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoDayCare::
	.incbin "data/tilesets/secondary/kantodaycare/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantodaycare/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantodaycare/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantodaycare/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantodaycare/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantodaycare/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantodaycare/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantodaycare/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantodaycare/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantodaycare/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantodaycare/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantodaycare/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantodaycare/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoDayCare::
	.incbin "data/tilesets/secondary/kantodaycare/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonTower::
	.incbin "data/tilesets/secondary/pokemontower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemontower/palettes/12.gbapal"

	.align 2
gTilesetTiles_PokemonTower::
	.incbin "data/tilesets/secondary/pokemontower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_VermilionCity::
	.incbin "data/tilesets/secondary/vermilioncity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/vermilioncity/palettes/12.gbapal"

	.align 2
gTilesetTiles_VermilionCity::
	.incbin "data/tilesets/secondary/vermilioncity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_VermilionCityGym::
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/vermilioncitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_VermilionCityGym::
	.incbin "data/tilesets/secondary/vermilioncitygym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonCity::
	.incbin "data/tilesets/secondary/celadoncity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadoncity/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeladonCity::
	.incbin "data/tilesets/secondary/celadoncity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonDepartmentStore::
	.incbin "data/tilesets/secondary/celadondepartmentstore/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadondepartmentstore/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadondepartmentstore/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadondepartmentstore/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadondepartmentstore/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadondepartmentstore/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadondepartmentstore/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadondepartmentstore/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadondepartmentstore/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadondepartmentstore/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadondepartmentstore/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadondepartmentstore/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadondepartmentstore/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeladonDepartmentStore::
	.incbin "data/tilesets/secondary/celadondepartmentstore/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SilphCo::
	.incbin "data/tilesets/secondary/silphco/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/silphco/palettes/12.gbapal"

	.align 2
gTilesetTiles_SilphCo::
	.incbin "data/tilesets/secondary/silphco/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_Condominiums::
	.incbin "data/tilesets/secondary/condominiums/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/condominiums/palettes/12.gbapal"

	.align 2
gTilesetTiles_Condominiums::
	.incbin "data/tilesets/secondary/condominiums/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GameCorner::
	.incbin "data/tilesets/secondary/gamecorner/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/gamecorner/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/gamecorner/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/gamecorner/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/gamecorner/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/gamecorner/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/gamecorner/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/gamecorner/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/gamecorner/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/gamecorner/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/gamecorner/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/gamecorner/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/gamecorner/palettes/12.gbapal"

	.align 2
gTilesetTiles_GameCorner::
	.incbin "data/tilesets/secondary/gamecorner/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonCityGym::
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadoncitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeladonCityGym::
	.incbin "data/tilesets/secondary/celadoncitygym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeladonHotel::
	.incbin "data/tilesets/secondary/celadonhotel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/celadonhotel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/celadonhotel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/celadonhotel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/celadonhotel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/celadonhotel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/celadonhotel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/celadonhotel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/celadonhotel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/celadonhotel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/celadonhotel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/celadonhotel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/celadonhotel/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeladonHotel::
	.incbin "data/tilesets/secondary/celadonhotel/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FuchsiaCity::
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacity/palettes/12.gbapal"

	.align 2
gTilesetTiles_FuchsiaCity::
	.incbin "data/tilesets/secondary/fuchsiacity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoSafariBuilding::
	.incbin "data/tilesets/secondary/kantosafaribuilding/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantosafaribuilding/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantosafaribuilding/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantosafaribuilding/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantosafaribuilding/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantosafaribuilding/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantosafaribuilding/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantosafaribuilding/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantosafaribuilding/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantosafaribuilding/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantosafaribuilding/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantosafaribuilding/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantosafaribuilding/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoSafariBuilding::
	.incbin "data/tilesets/secondary/kantosafaribuilding/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_FuchsiaCityGym::
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/fuchsiacitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_FuchsiaCityGym::
	.incbin "data/tilesets/secondary/fuchsiacitygym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CinnabarIsland::
	.incbin "data/tilesets/secondary/cinnabarisland/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cinnabarisland/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cinnabarisland/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cinnabarisland/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cinnabarisland/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cinnabarisland/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cinnabarisland/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cinnabarisland/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cinnabarisland/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cinnabarisland/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cinnabarisland/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cinnabarisland/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cinnabarisland/palettes/12.gbapal"

	.align 2
gTilesetTiles_CinnabarIsland::
	.incbin "data/tilesets/secondary/cinnabarisland/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CinnabarIslandGym::
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cinnabarislandgym/palettes/12.gbapal"

	.align 2
gTilesetTiles_CinnabarIslandGym::
	.incbin "data/tilesets/secondary/cinnabarislandgym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PokemonMansion::
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pokemonmansion/palettes/12.gbapal"

	.align 2
gTilesetTiles_PokemonMansion::
	.incbin "data/tilesets/secondary/pokemonmansion/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SaffronCity::
	.incbin "data/tilesets/secondary/saffroncity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/saffroncity/palettes/12.gbapal"

	.align 2
gTilesetTiles_SaffronCity::
	.incbin "data/tilesets/secondary/saffroncity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SaffronCityGym::
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/saffroncitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_SaffronCityGym::
	.incbin "data/tilesets/secondary/saffroncitygym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_IndigoPlateau::
	.incbin "data/tilesets/secondary/indigoplateau/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/indigoplateau/palettes/12.gbapal"

	.align 2
gTilesetTiles_IndigoPlateau::
	.incbin "data/tilesets/secondary/indigoplateau/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoPokemonLeague::
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantopokemonleague/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoPokemonLeague::
	.incbin "data/tilesets/secondary/kantopokemonleague/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoHallOfFame::
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantohalloffame/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoHallOfFame::
	.incbin "data/tilesets/secondary/kantohalloffame/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_ViridianForest::
	.incbin "data/tilesets/secondary/viridianforest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/viridianforest/palettes/12.gbapal"

	.align 2
gTilesetTiles_ViridianForest::
	.incbin "data/tilesets/secondary/viridianforest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_DiglettsCave::
	.incbin "data/tilesets/secondary/diglettscave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/diglettscave/palettes/12.gbapal"

	.align 2
gTilesetTiles_DiglettsCave::
	.incbin "data/tilesets/secondary/diglettscave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MtMoon::
	.incbin "data/tilesets/secondary/mtmoon/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mtmoon/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mtmoon/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mtmoon/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mtmoon/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mtmoon/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mtmoon/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mtmoon/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mtmoon/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mtmoon/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mtmoon/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mtmoon/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mtmoon/palettes/12.gbapal"

	.align 2
gTilesetTiles_MtMoon::
	.incbin "data/tilesets/secondary/mtmoon/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_UndergroundPass::
	.incbin "data/tilesets/secondary/undergroundpass/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/undergroundpass/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/undergroundpass/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/undergroundpass/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/undergroundpass/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/undergroundpass/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/undergroundpass/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/undergroundpass/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/undergroundpass/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/undergroundpass/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/undergroundpass/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/undergroundpass/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/undergroundpass/palettes/12.gbapal"

	.align 2
gTilesetTiles_UndergroundPass::
	.incbin "data/tilesets/secondary/undergroundpass/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RockTunnel::
	.incbin "data/tilesets/secondary/rocktunnel/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/rocktunnel/palettes/12.gbapal"

	.align 2
gTilesetTiles_RockTunnel::
	.incbin "data/tilesets/secondary/rocktunnel/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoPowerPlant::
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantopowerplant/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoPowerPlant::
	.incbin "data/tilesets/secondary/kantopowerplant/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeafoamIslands::
	.incbin "data/tilesets/secondary/seafoamislands/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/seafoamislands/palettes/12.gbapal"

	.align 2
gTilesetTiles_SeafoamIslands::
	.incbin "data/tilesets/secondary/seafoamislands/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeaCottage::
	.incbin "data/tilesets/secondary/seacottage/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/seacottage/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/seacottage/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/seacottage/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/seacottage/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/seacottage/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/seacottage/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/seacottage/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/seacottage/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/seacottage/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/seacottage/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/seacottage/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/seacottage/palettes/12.gbapal"

	.align 2
gTilesetTiles_SeaCottage::
	.incbin "data/tilesets/secondary/seacottage/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CeruleanCave::
	.incbin "data/tilesets/secondary/ceruleancave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ceruleancave/palettes/12.gbapal"

	.align 2
gTilesetTiles_CeruleanCave::
	.incbin "data/tilesets/secondary/ceruleancave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeviiIsles1::
	.incbin "data/tilesets/secondary/seviiisles1/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/seviiisles1/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/seviiisles1/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/seviiisles1/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/seviiisles1/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/seviiisles1/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/seviiisles1/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/seviiisles1/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/seviiisles1/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/seviiisles1/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/seviiisles1/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/seviiisles1/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/seviiisles1/palettes/12.gbapal"

	.align 2
gTilesetTiles_SeviiIsles1::
	.incbin "data/tilesets/secondary/seviiisles1/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoHarbor::
	.incbin "data/tilesets/secondary/kantoharbor/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantoharbor/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantoharbor/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantoharbor/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantoharbor/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantoharbor/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantoharbor/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantoharbor/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantoharbor/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantoharbor/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantoharbor/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantoharbor/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantoharbor/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoHarbor::
	.incbin "data/tilesets/secondary/kantoharbor/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MtEmber::
	.incbin "data/tilesets/secondary/mtember/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mtember/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mtember/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mtember/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mtember/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mtember/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mtember/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mtember/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mtember/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mtember/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mtember/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mtember/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mtember/palettes/12.gbapal"

	.align 2
gTilesetTiles_MtEmber::
	.incbin "data/tilesets/secondary/mtember/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BerryForest::
	.incbin "data/tilesets/secondary/berryforest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/berryforest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/berryforest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/berryforest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/berryforest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/berryforest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/berryforest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/berryforest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/berryforest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/berryforest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/berryforest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/berryforest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/berryforest/palettes/12.gbapal"

	.align 2
gTilesetTiles_BerryForest::
	.incbin "data/tilesets/secondary/berryforest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeviiIsles2::
	.incbin "data/tilesets/secondary/seviiisles2/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/seviiisles2/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/seviiisles2/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/seviiisles2/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/seviiisles2/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/seviiisles2/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/seviiisles2/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/seviiisles2/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/seviiisles2/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/seviiisles2/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/seviiisles2/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/seviiisles2/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/seviiisles2/palettes/12.gbapal"

	.align 2
gTilesetTiles_SeviiIsles2::
	.incbin "data/tilesets/secondary/seviiisles2/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_SeviiIsles3::
	.incbin "data/tilesets/secondary/seviiisles3/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/seviiisles3/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/seviiisles3/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/seviiisles3/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/seviiisles3/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/seviiisles3/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/seviiisles3/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/seviiisles3/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/seviiisles3/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/seviiisles3/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/seviiisles3/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/seviiisles3/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/seviiisles3/palettes/12.gbapal"

	.align 2
gTilesetTiles_SeviiIsles3::
	.incbin "data/tilesets/secondary/seviiisles3/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_DottedHole::
	.incbin "data/tilesets/secondary/dottedhole/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/dottedhole/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/dottedhole/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/dottedhole/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/dottedhole/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/dottedhole/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/dottedhole/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/dottedhole/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/dottedhole/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/dottedhole/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/dottedhole/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/dottedhole/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/dottedhole/palettes/12.gbapal"

	.align 2
gTilesetTiles_DottedHole::
	.incbin "data/tilesets/secondary/dottedhole/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_TanobyRuins::
	.incbin "data/tilesets/secondary/tanobyruins/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/tanobyruins/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/tanobyruins/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/tanobyruins/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/tanobyruins/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/tanobyruins/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/tanobyruins/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/tanobyruins/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/tanobyruins/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/tanobyruins/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/tanobyruins/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/tanobyruins/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/tanobyruins/palettes/12.gbapal"

	.align 2
gTilesetTiles_TanobyRuins::
	.incbin "data/tilesets/secondary/tanobyruins/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_KantoTrainerTower::
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/kantotrainertower/palettes/12.gbapal"

	.align 2
gTilesetTiles_KantoTrainerTower::
	.incbin "data/tilesets/secondary/kantotrainertower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_JohtoGeneral::
	.incbin "data/tilesets/primary/johtogeneral/palettes/00.gbapal"
	.incbin "data/tilesets/primary/johtogeneral/palettes/01.gbapal"
	.incbin "data/tilesets/primary/johtogeneral/palettes/02.gbapal"
	.incbin "data/tilesets/primary/johtogeneral/palettes/03.gbapal"
	.incbin "data/tilesets/primary/johtogeneral/palettes/04.gbapal"
	.incbin "data/tilesets/primary/johtogeneral/palettes/05.gbapal"
	.incbin "data/tilesets/primary/johtogeneral/palettes/06.gbapal"
	.incbin "data/tilesets/primary/johtogeneral/palettes/07.gbapal"
	.incbin "data/tilesets/primary/johtogeneral/palettes/08.gbapal"
	.incbin "data/tilesets/primary/johtogeneral/palettes/09.gbapal"
	.incbin "data/tilesets/primary/johtogeneral/palettes/10.gbapal"
	.incbin "data/tilesets/primary/johtogeneral/palettes/11.gbapal"
	.incbin "data/tilesets/primary/johtogeneral/palettes/12.gbapal"

	.align 2
gTilesetTiles_JohtoGeneral::
	.incbin "data/tilesets/primary/johtogeneral/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_JohtoBuilding::
	.incbin "data/tilesets/primary/johtobuilding/palettes/00.gbapal"
	.incbin "data/tilesets/primary/johtobuilding/palettes/01.gbapal"
	.incbin "data/tilesets/primary/johtobuilding/palettes/02.gbapal"
	.incbin "data/tilesets/primary/johtobuilding/palettes/03.gbapal"
	.incbin "data/tilesets/primary/johtobuilding/palettes/04.gbapal"
	.incbin "data/tilesets/primary/johtobuilding/palettes/05.gbapal"
	.incbin "data/tilesets/primary/johtobuilding/palettes/06.gbapal"
	.incbin "data/tilesets/primary/johtobuilding/palettes/07.gbapal"
	.incbin "data/tilesets/primary/johtobuilding/palettes/08.gbapal"
	.incbin "data/tilesets/primary/johtobuilding/palettes/09.gbapal"
	.incbin "data/tilesets/primary/johtobuilding/palettes/10.gbapal"
	.incbin "data/tilesets/primary/johtobuilding/palettes/11.gbapal"
	.incbin "data/tilesets/primary/johtobuilding/palettes/12.gbapal"

	.align 2
gTilesetTiles_JohtoBuilding::
	.incbin "data/tilesets/primary/johtobuilding/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_NewBarkTown::
	.incbin "data/tilesets/secondary/newbarktown/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/newbarktown/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/newbarktown/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/newbarktown/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/newbarktown/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/newbarktown/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/newbarktown/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/newbarktown/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/newbarktown/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/newbarktown/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/newbarktown/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/newbarktown/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/newbarktown/palettes/12.gbapal"

	.align 2
gTilesetTiles_NewBarkTown::
	.incbin "data/tilesets/secondary/newbarktown/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_JohtoBuilding1::
	.incbin "data/tilesets/secondary/johtobuilding1/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/johtobuilding1/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/johtobuilding1/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/johtobuilding1/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/johtobuilding1/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/johtobuilding1/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/johtobuilding1/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/johtobuilding1/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/johtobuilding1/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/johtobuilding1/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/johtobuilding1/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/johtobuilding1/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/johtobuilding1/palettes/12.gbapal"

	.align 2
gTilesetTiles_JohtoBuilding1::
	.incbin "data/tilesets/secondary/johtobuilding1/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_VioletCity::
	.incbin "data/tilesets/secondary/violetcity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/violetcity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/violetcity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/violetcity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/violetcity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/violetcity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/violetcity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/violetcity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/violetcity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/violetcity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/violetcity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/violetcity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/violetcity/palettes/12.gbapal"

	.align 2
gTilesetTiles_VioletCity::
	.incbin "data/tilesets/secondary/violetcity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_VioletCityGym::
	.incbin "data/tilesets/secondary/violetcitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/violetcitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/violetcitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/violetcitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/violetcitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/violetcitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/violetcitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/violetcitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/violetcitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/violetcitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/violetcitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/violetcitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/violetcitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_VioletCityGym::
	.incbin "data/tilesets/secondary/violetcitygym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_PagodaTower::
	.incbin "data/tilesets/secondary/pagodatower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/pagodatower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/pagodatower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/pagodatower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/pagodatower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/pagodatower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/pagodatower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/pagodatower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/pagodatower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/pagodatower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/pagodatower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/pagodatower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/pagodatower/palettes/12.gbapal"

	.align 2
gTilesetTiles_PagodaTower::
	.incbin "data/tilesets/secondary/pagodatower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_JohtoCave::
	.incbin "data/tilesets/secondary/johtocave/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/johtocave/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/johtocave/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/johtocave/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/johtocave/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/johtocave/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/johtocave/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/johtocave/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/johtocave/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/johtocave/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/johtocave/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/johtocave/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/johtocave/palettes/12.gbapal"

	.align 2
gTilesetTiles_JohtoCave::
	.incbin "data/tilesets/secondary/johtocave/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_AzaleaTown::
	.incbin "data/tilesets/secondary/azaleatown/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/azaleatown/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/azaleatown/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/azaleatown/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/azaleatown/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/azaleatown/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/azaleatown/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/azaleatown/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/azaleatown/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/azaleatown/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/azaleatown/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/azaleatown/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/azaleatown/palettes/12.gbapal"

	.align 2
gTilesetTiles_AzaleaTown::
	.incbin "data/tilesets/secondary/azaleatown/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_JohtoBikeShop::
	.incbin "data/tilesets/secondary/johtobikeshop/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/johtobikeshop/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/johtobikeshop/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/johtobikeshop/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/johtobikeshop/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/johtobikeshop/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/johtobikeshop/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/johtobikeshop/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/johtobikeshop/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/johtobikeshop/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/johtobikeshop/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/johtobikeshop/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/johtobikeshop/palettes/12.gbapal"

	.align 2
gTilesetTiles_JohtoBikeShop::
	.incbin "data/tilesets/secondary/johtobikeshop/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_AzaleaGym::
	.incbin "data/tilesets/secondary/azaleagym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/azaleagym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/azaleagym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/azaleagym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/azaleagym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/azaleagym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/azaleagym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/azaleagym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/azaleagym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/azaleagym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/azaleagym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/azaleagym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/azaleagym/palettes/12.gbapal"

	.align 2
gTilesetTiles_AzaleaGym::
	.incbin "data/tilesets/secondary/azaleagym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GoldenrodCity::
	.incbin "data/tilesets/secondary/goldenrodcity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/goldenrodcity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/goldenrodcity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/goldenrodcity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/goldenrodcity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/goldenrodcity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/goldenrodcity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/goldenrodcity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/goldenrodcity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/goldenrodcity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/goldenrodcity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/goldenrodcity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/goldenrodcity/palettes/12.gbapal"

	.align 2
gTilesetTiles_GoldenrodCity::
	.incbin "data/tilesets/secondary/goldenrodcity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_JohtoForest::
	.incbin "data/tilesets/secondary/johtoforest/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/johtoforest/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/johtoforest/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/johtoforest/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/johtoforest/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/johtoforest/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/johtoforest/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/johtoforest/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/johtoforest/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/johtoforest/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/johtoforest/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/johtoforest/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/johtoforest/palettes/12.gbapal"

	.align 2
gTilesetTiles_JohtoForest::
	.incbin "data/tilesets/secondary/johtoforest/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_JohtoDayCare::
	.incbin "data/tilesets/secondary/johtodaycare/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/johtodaycare/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/johtodaycare/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/johtodaycare/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/johtodaycare/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/johtodaycare/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/johtodaycare/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/johtodaycare/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/johtodaycare/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/johtodaycare/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/johtodaycare/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/johtodaycare/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/johtodaycare/palettes/12.gbapal"

	.align 2
gTilesetTiles_JohtoDayCare::
	.incbin "data/tilesets/secondary/johtodaycare/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_JohtoUnderground::
	.incbin "data/tilesets/secondary/johtounderground/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/johtounderground/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/johtounderground/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/johtounderground/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/johtounderground/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/johtounderground/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/johtounderground/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/johtounderground/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/johtounderground/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/johtounderground/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/johtounderground/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/johtounderground/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/johtounderground/palettes/12.gbapal"

	.align 2
gTilesetTiles_JohtoUnderground::
	.incbin "data/tilesets/secondary/johtounderground/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_GoldenrodGym::
	.incbin "data/tilesets/secondary/goldenrodgym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/goldenrodgym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/goldenrodgym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/goldenrodgym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/goldenrodgym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/goldenrodgym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/goldenrodgym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/goldenrodgym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/goldenrodgym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/goldenrodgym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/goldenrodgym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/goldenrodgym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/goldenrodgym/palettes/12.gbapal"

	.align 2
gTilesetTiles_GoldenrodGym::
	.incbin "data/tilesets/secondary/goldenrodgym/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_NationalPark::
	.incbin "data/tilesets/secondary/nationalpark/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/nationalpark/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/nationalpark/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/nationalpark/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/nationalpark/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/nationalpark/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/nationalpark/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/nationalpark/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/nationalpark/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/nationalpark/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/nationalpark/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/nationalpark/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/nationalpark/palettes/12.gbapal"

	.align 2
gTilesetTiles_NationalPark::
	.incbin "data/tilesets/secondary/nationalpark/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RuinsOfAlph::
	.incbin "data/tilesets/secondary/ruinsofalph/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ruinsofalph/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ruinsofalph/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ruinsofalph/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ruinsofalph/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ruinsofalph/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ruinsofalph/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ruinsofalph/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ruinsofalph/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ruinsofalph/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ruinsofalph/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ruinsofalph/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ruinsofalph/palettes/12.gbapal"

	.align 2
gTilesetTiles_RuinsOfAlph::
	.incbin "data/tilesets/secondary/ruinsofalph/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_EcruteakCity::
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/ecruteakcity/palettes/12.gbapal"

	.align 2
gTilesetTiles_EcruteakCity::
	.incbin "data/tilesets/secondary/ecruteakcity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_OlivineCity::
	.incbin "data/tilesets/secondary/olivinecity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/olivinecity/palettes/12.gbapal"

	.align 2
gTilesetTiles_OlivineCity::
	.incbin "data/tilesets/secondary/olivinecity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_CianwoodCity::
	.incbin "data/tilesets/secondary/cianwoodcity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/cianwoodcity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/cianwoodcity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/cianwoodcity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/cianwoodcity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/cianwoodcity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/cianwoodcity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/cianwoodcity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/cianwoodcity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/cianwoodcity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/cianwoodcity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/cianwoodcity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/cianwoodcity/palettes/12.gbapal"

	.align 2
gTilesetTiles_CianwoodCity::
	.incbin "data/tilesets/secondary/cianwoodcity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MahoganyTown::
	.incbin "data/tilesets/secondary/mahoganytown/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/mahoganytown/palettes/12.gbapal"

	.align 2
gTilesetTiles_MahoganyTown::
	.incbin "data/tilesets/secondary/mahoganytown/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_BlackthornCity::
	.incbin "data/tilesets/secondary/blackthorncity/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/blackthorncity/palettes/12.gbapal"

	.align 2
gTilesetTiles_BlackthornCity::
	.incbin "data/tilesets/secondary/blackthorncity/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_MagnetTrain::
	.incbin "data/tilesets/secondary/magnettrain/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/magnettrain/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/magnettrain/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/magnettrain/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/magnettrain/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/magnettrain/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/magnettrain/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/magnettrain/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/magnettrain/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/magnettrain/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/magnettrain/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/magnettrain/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/magnettrain/palettes/12.gbapal"

	.align 2
gTilesetTiles_MagnetTrain::
	.incbin "data/tilesets/secondary/magnettrain/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_JohtoDepartmentStore::
	.incbin "data/tilesets/secondary/johtodepartmentstore/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/johtodepartmentstore/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/johtodepartmentstore/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/johtodepartmentstore/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/johtodepartmentstore/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/johtodepartmentstore/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/johtodepartmentstore/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/johtodepartmentstore/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/johtodepartmentstore/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/johtodepartmentstore/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/johtodepartmentstore/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/johtodepartmentstore/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/johtodepartmentstore/palettes/12.gbapal"

	.align 2
gTilesetTiles_JohtoDepartmentStore::
	.incbin "data/tilesets/secondary/johtodepartmentstore/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_RadioTower::
	.incbin "data/tilesets/secondary/radiotower/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/radiotower/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/radiotower/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/radiotower/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/radiotower/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/radiotower/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/radiotower/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/radiotower/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/radiotower/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/radiotower/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/radiotower/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/radiotower/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/radiotower/palettes/12.gbapal"

	.align 2
gTilesetTiles_RadioTower::
	.incbin "data/tilesets/secondary/radiotower/tiles.4bpp.lz"

	.align 2
gTilesetPalettes_OlivineCityGym::
	.incbin "data/tilesets/secondary/olivinecitygym/palettes/00.gbapal"
	.incbin "data/tilesets/secondary/olivinecitygym/palettes/01.gbapal"
	.incbin "data/tilesets/secondary/olivinecitygym/palettes/02.gbapal"
	.incbin "data/tilesets/secondary/olivinecitygym/palettes/03.gbapal"
	.incbin "data/tilesets/secondary/olivinecitygym/palettes/04.gbapal"
	.incbin "data/tilesets/secondary/olivinecitygym/palettes/05.gbapal"
	.incbin "data/tilesets/secondary/olivinecitygym/palettes/06.gbapal"
	.incbin "data/tilesets/secondary/olivinecitygym/palettes/07.gbapal"
	.incbin "data/tilesets/secondary/olivinecitygym/palettes/08.gbapal"
	.incbin "data/tilesets/secondary/olivinecitygym/palettes/09.gbapal"
	.incbin "data/tilesets/secondary/olivinecitygym/palettes/10.gbapal"
	.incbin "data/tilesets/secondary/olivinecitygym/palettes/11.gbapal"
	.incbin "data/tilesets/secondary/olivinecitygym/palettes/12.gbapal"

	.align 2
gTilesetTiles_OlivineCityGym::
	.incbin "data/tilesets/secondary/olivinecitygym/tiles.4bpp.lz"
