	.align 2
gTileset_General::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_General
	.4byte gTilesetPalettes_General
	.4byte gMetatiles_General
	.4byte gMetatileAttributes_General
	.4byte InitTilesetAnim_General

	.align 2
gTileset_Petalburg::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Petalburg
	.4byte gTilesetPalettes_Petalburg
	.4byte gMetatiles_Petalburg
	.4byte gMetatileAttributes_Petalburg
	.4byte InitTilesetAnim_Petalburg

	.align 2
gTileset_Rustboro::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Rustboro
	.4byte gTilesetPalettes_Rustboro
	.4byte gMetatiles_Rustboro
	.4byte gMetatileAttributes_Rustboro
	.4byte InitTilesetAnim_Rustboro

	.align 2
gTileset_Dewford::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Dewford
	.4byte gTilesetPalettes_Dewford
	.4byte gMetatiles_Dewford
	.4byte gMetatileAttributes_Dewford
	.4byte InitTilesetAnim_Dewford

	.align 2
gTileset_Slateport::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Slateport
	.4byte gTilesetPalettes_Slateport
	.4byte gMetatiles_Slateport
	.4byte gMetatileAttributes_Slateport
	.4byte InitTilesetAnim_Slateport

	.align 2
gTileset_Mauville::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Mauville
	.4byte gTilesetPalettes_Mauville
	.4byte gMetatiles_Mauville
	.4byte gMetatileAttributes_Mauville
	.4byte InitTilesetAnim_Mauville

	.align 2
gTileset_Lavaridge::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Lavaridge
	.4byte gTilesetPalettes_Lavaridge
	.4byte gMetatiles_Lavaridge
	.4byte gMetatileAttributes_Lavaridge
	.4byte InitTilesetAnim_Lavaridge

	.align 2
gTileset_Fallarbor::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Fallarbor
	.4byte gTilesetPalettes_Fallarbor
	.4byte gMetatiles_Fallarbor
	.4byte gMetatileAttributes_Fallarbor
	.4byte InitTilesetAnim_Fallarbor

	.align 2
gTileset_Fortree::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Fortree
	.4byte gTilesetPalettes_Fortree
	.4byte gMetatiles_Fortree
	.4byte gMetatileAttributes_Fortree
	.4byte InitTilesetAnim_Fortree

	.align 2
gTileset_Lilycove::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Lilycove
	.4byte gTilesetPalettes_Lilycove
	.4byte gMetatiles_Lilycove
	.4byte gMetatileAttributes_Lilycove
	.4byte InitTilesetAnim_Lilycove

	.align 2
gTileset_Mossdeep::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Mossdeep
	.4byte gTilesetPalettes_Mossdeep
	.4byte gMetatiles_Mossdeep
	.4byte gMetatileAttributes_Mossdeep
	.4byte InitTilesetAnim_Mossdeep

	.align 2
gTileset_EverGrande::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_EverGrande
	.4byte gTilesetPalettes_EverGrande
	.4byte gMetatiles_EverGrande
	.4byte gMetatileAttributes_EverGrande
	.4byte InitTilesetAnim_EverGrande

	.align 2
gTileset_Pacifidlog::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Pacifidlog
	.4byte gTilesetPalettes_Pacifidlog
	.4byte gMetatiles_Pacifidlog
	.4byte gMetatileAttributes_Pacifidlog
	.4byte InitTilesetAnim_Pacifidlog

	.align 2
gTileset_Sootopolis::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Sootopolis
	.4byte gTilesetPalettes_Sootopolis
	.4byte gMetatiles_Sootopolis
	.4byte gMetatileAttributes_Sootopolis
	.4byte InitTilesetAnim_Sootopolis

	.align 2
gTileset_BattleFrontierOutsideWest::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontierOutsideWest
	.4byte gTilesetPalettes_BattleFrontierOutsideWest
	.4byte gMetatiles_BattleFrontierOutsideWest
	.4byte gMetatileAttributes_BattleFrontierOutsideWest
	.4byte InitTilesetAnim_BattleFrontierOutsideWest

	.align 2
gTileset_BattleFrontierOutsideEast::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontierOutsideEast
	.4byte gTilesetPalettes_BattleFrontierOutsideEast
	.4byte gMetatiles_BattleFrontierOutsideEast
	.4byte gMetatileAttributes_BattleFrontierOutsideEast
	.4byte InitTilesetAnim_BattleFrontierOutsideEast

	.align 2
gTileset_Building::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_InsideBuilding
	.4byte gTilesetPalettes_InsideBuilding
	.4byte gMetatiles_InsideBuilding
	.4byte gMetatileAttributes_InsideBuilding
	.4byte InitTilesetAnim_Building

	.align 2
gTileset_Shop::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Shop
	.4byte gTilesetPalettes_Shop
	.4byte gMetatiles_Shop
	.4byte gMetatileAttributes_Shop
	.4byte NULL @ animation callback

	.align 2
gTileset_PokemonCenter::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonCenter
	.4byte gTilesetPalettes_PokemonCenter
	.4byte gMetatiles_PokemonCenter
	.4byte gMetatileAttributes_PokemonCenter
	.4byte NULL @ animation callback

	.align 2
gTileset_Cave::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Cave
	.4byte gTilesetPalettes_Cave
	.4byte gMetatiles_Cave
	.4byte gMetatileAttributes_Cave
	.4byte InitTilesetAnim_Cave

	.align 2
gTileset_PokemonSchool::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonSchool
	.4byte gTilesetPalettes_PokemonSchool
	.4byte gMetatiles_PokemonSchool
	.4byte gMetatileAttributes_PokemonSchool
	.4byte NULL @ animation callback

	.align 2
gTileset_PokemonFanClub::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonFanClub
	.4byte gTilesetPalettes_PokemonFanClub
	.4byte gMetatiles_PokemonFanClub
	.4byte gMetatileAttributes_PokemonFanClub
	.4byte NULL @ animation callback

	.align 2
gTileset_Unused1::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Unused1
	.4byte gTilesetPalettes_Unused1
	.4byte gMetatiles_Unused1
	.4byte gMetatileAttributes_Unused1
	.4byte NULL @ animation callback

	.align 2
gTileset_MeteorFalls::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MeteorFalls
	.4byte gTilesetPalettes_MeteorFalls
	.4byte gMetatiles_MeteorFalls
	.4byte gMetatileAttributes_MeteorFalls
	.4byte NULL @ animation callback

	.align 2
gTileset_OceanicMuseum::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_OceanicMuseum
	.4byte gTilesetPalettes_OceanicMuseum
	.4byte gMetatiles_OceanicMuseum
	.4byte gMetatileAttributes_OceanicMuseum
	.4byte NULL @ animation callback

	.align 2
gTileset_CableClub::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_CableClub
	.4byte gTilesetPalettes_CableClub
	.4byte gMetatiles_CableClub
	.4byte gMetatileAttributes_CableClub
	.4byte NULL @ animation callback

	.align 2
gTileset_SeashoreHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SeashoreHouse
	.4byte gTilesetPalettes_SeashoreHouse
	.4byte gMetatiles_SeashoreHouse
	.4byte gMetatileAttributes_SeashoreHouse
	.4byte NULL @ animation callback

	.align 2
gTileset_PrettyPetalFlowerShop::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PrettyPetalFlowerShop
	.4byte gTilesetPalettes_PrettyPetalFlowerShop
	.4byte gMetatiles_PrettyPetalFlowerShop
	.4byte gMetatileAttributes_PrettyPetalFlowerShop
	.4byte NULL @ animation callback

	.align 2
gTileset_PokemonDayCare::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PokemonDayCare
	.4byte gTilesetPalettes_PokemonDayCare
	.4byte gMetatiles_PokemonDayCare
	.4byte gMetatileAttributes_PokemonDayCare
	.4byte NULL @ animation callback

	.align 2
gTileset_Facility::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Facility
	.4byte gTilesetPalettes_Facility
	.4byte gMetatiles_Facility
	.4byte gMetatileAttributes_Facility
	.4byte NULL @ animation callback

	.align 2
gTileset_BikeShop::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BikeShop
	.4byte gTilesetPalettes_BikeShop
	.4byte gMetatiles_BikeShop
	.4byte gMetatileAttributes_BikeShop
	.4byte InitTilesetAnim_BikeShop

	.align 2
gTileset_RusturfTunnel::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_RusturfTunnel
	.4byte gTilesetPalettes_RusturfTunnel
	.4byte gMetatiles_RusturfTunnel
	.4byte gMetatileAttributes_RusturfTunnel
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseBrownCave::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseBrownCave
	.4byte gTilesetPalettes_SecretBaseBrownCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseTree::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseTree
	.4byte gTilesetPalettes_SecretBaseTree
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseShrub::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseShrub
	.4byte gTilesetPalettes_SecretBaseShrub
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseBlueCave::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseBlueCave
	.4byte gTilesetPalettes_SecretBaseBlueCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseYellowCave::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseYellowCave
	.4byte gTilesetPalettes_SecretBaseYellowCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBaseRedCave::
	.byte FALSE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBaseRedCave
	.4byte gTilesetPalettes_SecretBaseRedCave
	.4byte gMetatiles_SecretBaseSecondary
	.4byte gMetatileAttributes_SecretBaseSecondary
	.4byte NULL @ animation callback

	.align 2
gTileset_InsideOfTruck::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_InsideOfTruck
	.4byte gTilesetPalettes_InsideOfTruck
	.4byte gMetatiles_InsideOfTruck
	.4byte gMetatileAttributes_InsideOfTruck
	.4byte NULL @ animation callback

	.align 2
gTileset_Unused2::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Unused2
	.4byte gTilesetPalettes_Unused2
	.4byte gMetatiles_Unused2
	.4byte gMetatileAttributes_Unused2
	.4byte NULL @ animation callback

	.align 2
gTileset_Contest::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Contest
	.4byte gTilesetPalettes_Contest
	.4byte gMetatiles_Contest
	.4byte gMetatileAttributes_Contest
	.4byte NULL @ animation callback

	.align 2
gTileset_LilycoveMuseum::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_LilycoveMuseum
	.4byte gTilesetPalettes_LilycoveMuseum
	.4byte gMetatiles_LilycoveMuseum
	.4byte gMetatileAttributes_LilycoveMuseum
	.4byte NULL @ animation callback

	.align 2
gTileset_BrendansMaysHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BrendansMaysHouse
	.4byte gTilesetPalettes_BrendansMaysHouse
	.4byte gMetatiles_BrendansMaysHouse
	.4byte gMetatileAttributes_BrendansMaysHouse
	.4byte NULL @ animation callback

	.align 2
gTileset_Lab::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Lab
	.4byte gTilesetPalettes_Lab
	.4byte gMetatiles_Lab
	.4byte gMetatileAttributes_Lab
	.4byte NULL @ animation callback

	.align 2
gTileset_Underwater::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_Underwater
	.4byte gTilesetPalettes_Underwater
	.4byte gMetatiles_Underwater
	.4byte gMetatileAttributes_Underwater
	.4byte InitTilesetAnim_Underwater

	.align 2
gTileset_PetalburgGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_PetalburgGym
	.4byte gTilesetPalettes_PetalburgGym
	.4byte gMetatiles_PetalburgGym
	.4byte gMetatileAttributes_PetalburgGym
	.4byte NULL @ animation callback

	.align 2
gTileset_SootopolisGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SootopolisGym
	.4byte gTilesetPalettes_SootopolisGym
	.4byte gMetatiles_SootopolisGym
	.4byte gMetatileAttributes_SootopolisGym
	.4byte InitTilesetAnim_SootopolisGym

	.align 2
gTileset_GenericBuilding::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_GenericBuilding
	.4byte gTilesetPalettes_GenericBuilding
	.4byte gMetatiles_GenericBuilding
	.4byte gMetatileAttributes_GenericBuilding
	.4byte NULL @ animation callback

	.align 2
gTileset_MauvilleGameCorner::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MauvilleGameCorner
	.4byte gTilesetPalettes_MauvilleGameCorner
	.4byte gMetatiles_MauvilleGameCorner
	.4byte gMetatileAttributes_MauvilleGameCorner
	.4byte NULL @ animation callback

	.align 2
gTileset_RustboroGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_RustboroGym
	.4byte gTilesetPalettes_RustboroGym
	.4byte gMetatiles_RustboroGym
	.4byte gMetatileAttributes_RustboroGym
	.4byte NULL @ animation callback

	.align 2
gTileset_DewfordGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_DewfordGym
	.4byte gTilesetPalettes_DewfordGym
	.4byte gMetatiles_DewfordGym
	.4byte gMetatileAttributes_DewfordGym
	.4byte NULL @ animation callback

	.align 2
gTileset_MauvilleGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MauvilleGym
	.4byte gTilesetPalettes_MauvilleGym
	.4byte gMetatiles_MauvilleGym
	.4byte gMetatileAttributes_MauvilleGym
	.4byte InitTilesetAnim_MauvilleGym

	.align 2
gTileset_LavaridgeGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_LavaridgeGym
	.4byte gTilesetPalettes_LavaridgeGym
	.4byte gMetatiles_LavaridgeGym
	.4byte gMetatileAttributes_LavaridgeGym
	.4byte NULL @ animation callback

	.align 2
gTileset_TrickHousePuzzle::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_TrickHousePuzzle
	.4byte gTilesetPalettes_TrickHousePuzzle
	.4byte gMetatiles_TrickHousePuzzle
	.4byte gMetatileAttributes_TrickHousePuzzle
	.4byte NULL @ animation callback

	.align 2
gTileset_FortreeGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_FortreeGym
	.4byte gTilesetPalettes_FortreeGym
	.4byte gMetatiles_FortreeGym
	.4byte gMetatileAttributes_FortreeGym
	.4byte NULL @ animation callback

	.align 2
gTileset_MossdeepGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MossdeepGym
	.4byte gTilesetPalettes_MossdeepGym
	.4byte gMetatiles_MossdeepGym
	.4byte gMetatileAttributes_MossdeepGym
	.4byte NULL @ animation callback

	.align 2
gTileset_InsideShip::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_InsideShip
	.4byte gTilesetPalettes_InsideShip
	.4byte gMetatiles_InsideShip
	.4byte gMetatileAttributes_InsideShip
	.4byte NULL @ animation callback

	.align 2
gTileset_SecretBase::
	.byte FALSE @ is compressed
	.byte FALSE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_SecretBase
	.4byte gTilesetPalettes_SecretBase
	.4byte gMetatiles_SecretBasePrimary
	.4byte gMetatileAttributes_SecretBasePrimary
	.4byte NULL @ animation callback

	.align 2
gTilesetPointer_SecretBase::
	.4byte gTileset_SecretBase

	.align 2
gTilesetPointer_SecretBaseRedCave::
	.4byte gTileset_SecretBaseRedCave

	.align 2
gTileset_EliteFour::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_EliteFour
	.4byte gTilesetPalettes_EliteFour
	.4byte gMetatiles_EliteFour
	.4byte gMetatileAttributes_EliteFour
	.4byte InitTilesetAnim_EliteFour

	.align 2
gTileset_BattleFrontier::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontier
	.4byte gTilesetPalettes_BattleFrontier
	.4byte gMetatiles_BattleFrontier
	.4byte gMetatileAttributes_BattleFrontier
	.4byte NULL @ animation callback

	.align 2
gTileset_BattlePalace::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattlePalace
	.4byte gTilesetPalettes_BattlePalace
	.4byte gMetatiles_BattlePalace
	.4byte gMetatileAttributes_BattlePalace
	.4byte NULL @ animation callback

	.align 2
gTileset_BattleDome::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleDome
	.4byte gTilesetPalettes_BattleDome
	.4byte gMetatiles_BattleDome
	.4byte gMetatileAttributes_BattleDome
	.4byte InitTilesetAnim_BattleDome

	.align 2
gTileset_BattleFactory::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFactory
	.4byte gTilesetPalettes_BattleFactory
	.4byte gMetatiles_BattleFactory
	.4byte gMetatileAttributes_BattleFactory
	.4byte NULL @ animation callback

	.align 2
gTileset_BattlePike::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattlePike
	.4byte gTilesetPalettes_BattlePike
	.4byte gMetatiles_BattlePike
	.4byte gMetatileAttributes_BattlePike
	.4byte NULL @ animation callback

	.align 2
gTileset_BattleArena::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleArena
	.4byte gTilesetPalettes_BattleArena
	.4byte gMetatiles_BattleArena
	.4byte gMetatileAttributes_BattleArena
	.4byte NULL @ animation callback

	.align 2
gTileset_BattlePyramid::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattlePyramid
	.4byte gTilesetPalettes_BattlePyramid
	.4byte gMetatiles_BattlePyramid
	.4byte gMetatileAttributes_BattlePyramid
	.4byte InitTilesetAnim_BattlePyramid

	.align 2
gTileset_MirageTower::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MirageTower
	.4byte gTilesetPalettes_MirageTower
	.4byte gMetatiles_MirageTower
	.4byte gMetatileAttributes_MirageTower
	.4byte NULL @ animation callback

	.align 2
gTileset_MossdeepGameCorner::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MossdeepGameCorner
	.4byte gTilesetPalettes_MossdeepGameCorner
	.4byte gMetatiles_MossdeepGameCorner
	.4byte gMetatileAttributes_MossdeepGameCorner
	.4byte NULL @ animation callback

	.align 2
gTileset_IslandHarbor::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_IslandHarbor
	.4byte gTilesetPalettes_IslandHarbor
	.4byte gMetatiles_IslandHarbor
	.4byte gMetatileAttributes_IslandHarbor
	.4byte NULL @ animation callback

	.align 2
gTileset_TrainerHill::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_TrainerHill
	.4byte gTilesetPalettes_TrainerHill
	.4byte gMetatiles_TrainerHill
	.4byte gMetatileAttributes_TrainerHill
	.4byte NULL @ animation callback

	.align 2
gTileset_NavelRock::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_NavelRock
	.4byte gTilesetPalettes_NavelRock
	.4byte gMetatiles_NavelRock
	.4byte gMetatileAttributes_NavelRock
	.4byte NULL @ animation callback

	.align 2
gTileset_BattleFrontierRankingHall::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleFrontierRankingHall
	.4byte gTilesetPalettes_BattleFrontierRankingHall
	.4byte gMetatiles_BattleFrontierRankingHall
	.4byte gMetatileAttributes_BattleFrontierRankingHall
	.4byte NULL @ animation callback

	.align 2
gTileset_BattleTent::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_BattleTent
	.4byte gTilesetPalettes_BattleTent
	.4byte gMetatiles_BattleTent
	.4byte gMetatileAttributes_BattleTent
	.4byte NULL @ animation callback

	.align 2
gTileset_MysteryEventsHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_MysteryEventsHouse
	.4byte gTilesetPalettes_MysteryEventsHouse
	.4byte gMetatiles_MysteryEventsHouse
	.4byte gMetatileAttributes_MysteryEventsHouse
	.4byte NULL @ animation callback

	.align 2
gTileset_UnionRoom::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary tileset
	.2byte 0 @ padding
	.4byte gTilesetTiles_UnionRoom
	.4byte gTilesetPalettes_UnionRoom
	.4byte gMetatiles_UnionRoom
	.4byte gMetatileAttributes_UnionRoom
	.4byte NULL @ animation callback

	.align 2
gTileset_KantoGeneral::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_KantoGeneral
	.4byte gTilesetPalettes_KantoGeneral
	.4byte gMetatiles_KantoGeneral
	.4byte gMetatileAttributes_KantoGeneral
	.4byte InitTilesetAnim_KantoGeneral

	.align 2
gTileset_PalletTown::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PalletTown
	.4byte gTilesetPalettes_PalletTown
	.4byte gMetatiles_PalletTown
	.4byte gMetatileAttributes_PalletTown
	.4byte NULL

	.align 2
gTileset_ViridianCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_ViridianCity
	.4byte gTilesetPalettes_ViridianCity
	.4byte gMetatiles_ViridianCity
	.4byte gMetatileAttributes_ViridianCity
	.4byte NULL

	.align 2
gTileset_KantoBuilding::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_KantoBuilding
	.4byte gTilesetPalettes_KantoBuilding
	.4byte gMetatiles_KantoBuilding
	.4byte gMetatileAttributes_KantoBuilding
	.4byte NULL

	.align 2
gTileset_KantoBuilding1::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_KantoBuilding1
	.4byte gTilesetPalettes_KantoBuilding1
	.4byte gMetatiles_KantoBuilding1
	.4byte gMetatileAttributes_KantoBuilding1
	.4byte NULL

	.align 2
gTileset_KantoBuilding2::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_KantoBuilding2
	.4byte gTilesetPalettes_KantoBuilding2
	.4byte gMetatiles_KantoBuilding2
	.4byte gMetatileAttributes_KantoBuilding2
	.4byte NULL

	.align 2
gTileset_KantoOaksLab::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_KantoOaksLab
	.4byte gTilesetPalettes_KantoOaksLab
	.4byte gMetatiles_KantoOaksLab
	.4byte gMetatileAttributes_KantoOaksLab
	.4byte NULL

	.align 2
gTileset_ViridianCityGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_ViridianCityGym
	.4byte gTilesetPalettes_ViridianCityGym
	.4byte gMetatiles_ViridianCityGym
	.4byte gMetatileAttributes_ViridianCityGym
	.4byte NULL

	.align 2
gTileset_KantoBuilding3::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_KantoBuilding3
	.4byte gTilesetPalettes_KantoBuilding3
	.4byte gMetatiles_KantoBuilding3
	.4byte gMetatileAttributes_KantoBuilding3
	.4byte NULL

	.align 2
gTileset_KantoPokeMart::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_KantoPokeMart
	.4byte gTilesetPalettes_KantoPokeMart
	.4byte gMetatiles_KantoPokeMart
	.4byte gMetatileAttributes_KantoPokeMart
	.4byte NULL

	.align 2
gTileset_KantoPokeCenter::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_KantoPokeCenter
	.4byte gTilesetPalettes_KantoPokeCenter
	.4byte gMetatiles_KantoPokeCenter
	.4byte gMetatileAttributes_KantoPokeCenter
	.4byte NULL

	.align 2
gTileset_PewterCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PewterCity
	.4byte gTilesetPalettes_PewterCity
	.4byte gMetatiles_PewterCity
	.4byte gMetatileAttributes_PewterCity
	.4byte NULL

	.align 2
gTileset_PewterCityMuseum::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PewterCityMuseum
	.4byte gTilesetPalettes_PewterCityMuseum
	.4byte gMetatiles_PewterCityMuseum
	.4byte gMetatileAttributes_PewterCityMuseum
	.4byte NULL

	.align 2
gTileset_PewterCityGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PewterCityGym
	.4byte gTilesetPalettes_PewterCityGym
	.4byte gMetatiles_PewterCityGym
	.4byte gMetatileAttributes_PewterCityGym
	.4byte NULL

	.align 2
gTileset_CeruleanCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeruleanCity
	.4byte gTilesetPalettes_CeruleanCity
	.4byte gMetatiles_CeruleanCity
	.4byte gMetatileAttributes_CeruleanCity
	.4byte NULL

	.align 2
gTileset_CeruleanCityCrimeHouse::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeruleanCityCrimeHouse
	.4byte gTilesetPalettes_CeruleanCityCrimeHouse
	.4byte gMetatiles_CeruleanCityCrimeHouse
	.4byte gMetatileAttributes_CeruleanCityCrimeHouse
	.4byte NULL

	.align 2
gTileset_CeruleanCityGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeruleanCityGym
	.4byte gTilesetPalettes_CeruleanCityGym
	.4byte gMetatiles_CeruleanCityGym
	.4byte gMetatileAttributes_CeruleanCityGym
	.4byte NULL

	.align 2
gTileset_CeruleanCityBikeShop::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeruleanCityBikeShop
	.4byte gTilesetPalettes_CeruleanCityBikeShop
	.4byte gMetatiles_CeruleanCityBikeShop
	.4byte gMetatileAttributes_CeruleanCityBikeShop
	.4byte NULL

	.align 2
gTileset_LavenderTown::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_LavenderTown
	.4byte gTilesetPalettes_LavenderTown
	.4byte gMetatiles_LavenderTown
	.4byte gMetatileAttributes_LavenderTown
	.4byte NULL

	.align 2
gTileset_KantoDayCare::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_KantoDayCare
	.4byte gTilesetPalettes_KantoDayCare
	.4byte gMetatiles_KantoDayCare
	.4byte gMetatileAttributes_KantoDayCare
	.4byte NULL

	.align 2
gTileset_PokemonTower::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PokemonTower
	.4byte gTilesetPalettes_PokemonTower
	.4byte gMetatiles_PokemonTower
	.4byte gMetatileAttributes_PokemonTower
	.4byte NULL

	.align 2
gTileset_VermilionCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_VermilionCity
	.4byte gTilesetPalettes_VermilionCity
	.4byte gMetatiles_VermilionCity
	.4byte gMetatileAttributes_VermilionCity
	.4byte NULL

	.align 2
gTileset_VermilionCityGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_VermilionCityGym
	.4byte gTilesetPalettes_VermilionCityGym
	.4byte gMetatiles_VermilionCityGym
	.4byte gMetatileAttributes_VermilionCityGym
	.4byte NULL

	.align 2
gTileset_CeladonCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeladonCity
	.4byte gTilesetPalettes_CeladonCity
	.4byte gMetatiles_CeladonCity
	.4byte gMetatileAttributes_CeladonCity
	.4byte NULL

	.align 2
gTileset_CeladonDepartmentStore::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeladonDepartmentStore
	.4byte gTilesetPalettes_CeladonDepartmentStore
	.4byte gMetatiles_CeladonDepartmentStore
	.4byte gMetatileAttributes_CeladonDepartmentStore
	.4byte NULL

	.align 2
gTileset_SilphCo::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SilphCo
	.4byte gTilesetPalettes_SilphCo
	.4byte gMetatiles_SilphCo
	.4byte gMetatileAttributes_SilphCo
	.4byte NULL

	.align 2
gTileset_Condominiums::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_Condominiums
	.4byte gTilesetPalettes_Condominiums
	.4byte gMetatiles_Condominiums
	.4byte gMetatileAttributes_Condominiums
	.4byte NULL

	.align 2
gTileset_GameCorner::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_GameCorner
	.4byte gTilesetPalettes_GameCorner
	.4byte gMetatiles_GameCorner
	.4byte gMetatileAttributes_GameCorner
	.4byte NULL

	.align 2
gTileset_CeladonCityGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeladonCityGym
	.4byte gTilesetPalettes_CeladonCityGym
	.4byte gMetatiles_CeladonCityGym
	.4byte gMetatileAttributes_CeladonCityGym
	.4byte NULL

	.align 2
gTileset_CeladonHotel::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeladonHotel
	.4byte gTilesetPalettes_CeladonHotel
	.4byte gMetatiles_CeladonHotel
	.4byte gMetatileAttributes_CeladonHotel
	.4byte NULL

	.align 2
gTileset_FuchsiaCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_FuchsiaCity
	.4byte gTilesetPalettes_FuchsiaCity
	.4byte gMetatiles_FuchsiaCity
	.4byte gMetatileAttributes_FuchsiaCity
	.4byte NULL

	.align 2
gTileset_KantoSafariBuilding::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_KantoSafariBuilding
	.4byte gTilesetPalettes_KantoSafariBuilding
	.4byte gMetatiles_KantoSafariBuilding
	.4byte gMetatileAttributes_KantoSafariBuilding
	.4byte NULL

	.align 2
gTileset_FuchsiaCityGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_FuchsiaCityGym
	.4byte gTilesetPalettes_FuchsiaCityGym
	.4byte gMetatiles_FuchsiaCityGym
	.4byte gMetatileAttributes_FuchsiaCityGym
	.4byte NULL

	.align 2
gTileset_CinnabarIsland::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CinnabarIsland
	.4byte gTilesetPalettes_CinnabarIsland
	.4byte gMetatiles_CinnabarIsland
	.4byte gMetatileAttributes_CinnabarIsland
	.4byte NULL

	.align 2
gTileset_CinnabarIslandGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CinnabarIslandGym
	.4byte gTilesetPalettes_CinnabarIslandGym
	.4byte gMetatiles_CinnabarIslandGym
	.4byte gMetatileAttributes_CinnabarIslandGym
	.4byte NULL

	.align 2
gTileset_PokemonMansion::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PokemonMansion
	.4byte gTilesetPalettes_PokemonMansion
	.4byte gMetatiles_PokemonMansion
	.4byte gMetatileAttributes_PokemonMansion
	.4byte NULL

	.align 2
gTileset_SaffronCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SaffronCity
	.4byte gTilesetPalettes_SaffronCity
	.4byte gMetatiles_SaffronCity
	.4byte gMetatileAttributes_SaffronCity
	.4byte NULL

	.align 2
gTileset_SaffronCityGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SaffronCityGym
	.4byte gTilesetPalettes_SaffronCityGym
	.4byte gMetatiles_SaffronCityGym
	.4byte gMetatileAttributes_SaffronCityGym
	.4byte NULL

	.align 2
gTileset_IndigoPlateau::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_IndigoPlateau
	.4byte gTilesetPalettes_IndigoPlateau
	.4byte gMetatiles_IndigoPlateau
	.4byte gMetatileAttributes_IndigoPlateau
	.4byte NULL

	.align 2
gTileset_KantoPokemonLeague::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_KantoPokemonLeague
	.4byte gTilesetPalettes_KantoPokemonLeague
	.4byte gMetatiles_KantoPokemonLeague
	.4byte gMetatileAttributes_KantoPokemonLeague
	.4byte NULL

	.align 2
gTileset_KantoHallOfFame::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_KantoHallOfFame
	.4byte gTilesetPalettes_KantoHallOfFame
	.4byte gMetatiles_KantoHallOfFame
	.4byte gMetatileAttributes_KantoHallOfFame
	.4byte NULL

	.align 2
gTileset_ViridianForest::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_ViridianForest
	.4byte gTilesetPalettes_ViridianForest
	.4byte gMetatiles_ViridianForest
	.4byte gMetatileAttributes_ViridianForest
	.4byte NULL

	.align 2
gTileset_DiglettsCave::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_DiglettsCave
	.4byte gTilesetPalettes_DiglettsCave
	.4byte gMetatiles_DiglettsCave
	.4byte gMetatileAttributes_DiglettsCave
	.4byte NULL

	.align 2
gTileset_MtMoon::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_MtMoon
	.4byte gTilesetPalettes_MtMoon
	.4byte gMetatiles_MtMoon
	.4byte gMetatileAttributes_MtMoon
	.4byte NULL

	.align 2
gTileset_UndergroundPass::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_UndergroundPass
	.4byte gTilesetPalettes_UndergroundPass
	.4byte gMetatiles_UndergroundPass
	.4byte gMetatileAttributes_UndergroundPass
	.4byte NULL

	.align 2
gTileset_RockTunnel::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_RockTunnel
	.4byte gTilesetPalettes_RockTunnel
	.4byte gMetatiles_RockTunnel
	.4byte gMetatileAttributes_RockTunnel
	.4byte NULL

	.align 2
gTileset_KantoPowerPlant::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_KantoPowerPlant
	.4byte gTilesetPalettes_KantoPowerPlant
	.4byte gMetatiles_KantoPowerPlant
	.4byte gMetatileAttributes_KantoPowerPlant
	.4byte NULL

	.align 2
gTileset_SeafoamIslands::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SeafoamIslands
	.4byte gTilesetPalettes_SeafoamIslands
	.4byte gMetatiles_SeafoamIslands
	.4byte gMetatileAttributes_SeafoamIslands
	.4byte NULL

	.align 2
gTileset_SeaCottage::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SeaCottage
	.4byte gTilesetPalettes_SeaCottage
	.4byte gMetatiles_SeaCottage
	.4byte gMetatileAttributes_SeaCottage
	.4byte NULL

	.align 2
gTileset_CeruleanCave::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_CeruleanCave
	.4byte gTilesetPalettes_CeruleanCave
	.4byte gMetatiles_CeruleanCave
	.4byte gMetatileAttributes_CeruleanCave
	.4byte NULL

	.align 2
gTileset_SeviiIsles1::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SeviiIsles1
	.4byte gTilesetPalettes_SeviiIsles1
	.4byte gMetatiles_SeviiIsles1
	.4byte gMetatileAttributes_SeviiIsles1
	.4byte NULL

	.align 2
gTileset_KantoHarbor::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_KantoHarbor
	.4byte gTilesetPalettes_KantoHarbor
	.4byte gMetatiles_KantoHarbor
	.4byte gMetatileAttributes_KantoHarbor
	.4byte NULL

	.align 2
gTileset_MtEmber::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_MtEmber
	.4byte gTilesetPalettes_MtEmber
	.4byte gMetatiles_MtEmber
	.4byte gMetatileAttributes_MtEmber
	.4byte NULL

	.align 2
gTileset_BerryForest::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_BerryForest
	.4byte gTilesetPalettes_BerryForest
	.4byte gMetatiles_BerryForest
	.4byte gMetatileAttributes_BerryForest
	.4byte NULL

	.align 2
gTileset_SeviiIsles2::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SeviiIsles2
	.4byte gTilesetPalettes_SeviiIsles2
	.4byte gMetatiles_SeviiIsles2
	.4byte gMetatileAttributes_SeviiIsles2
	.4byte NULL

	.align 2
gTileset_SeviiIsles3::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_SeviiIsles3
	.4byte gTilesetPalettes_SeviiIsles3
	.4byte gMetatiles_SeviiIsles3
	.4byte gMetatileAttributes_SeviiIsles3
	.4byte NULL

	.align 2
gTileset_DottedHole::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_DottedHole
	.4byte gTilesetPalettes_DottedHole
	.4byte gMetatiles_DottedHole
	.4byte gMetatileAttributes_DottedHole
	.4byte NULL

	.align 2
gTileset_TanobyRuins::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_TanobyRuins
	.4byte gTilesetPalettes_TanobyRuins
	.4byte gMetatiles_TanobyRuins
	.4byte gMetatileAttributes_TanobyRuins
	.4byte NULL

	.align 2
gTileset_KantoTrainerTower::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_KantoTrainerTower
	.4byte gTilesetPalettes_KantoTrainerTower
	.4byte gMetatiles_KantoTrainerTower
	.4byte gMetatileAttributes_KantoTrainerTower
	.4byte NULL

	.align 2
gTileset_JohtoGeneral::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_JohtoGeneral
	.4byte gTilesetPalettes_JohtoGeneral
	.4byte gMetatiles_JohtoGeneral
	.4byte gMetatileAttributes_JohtoGeneral
	.4byte InitTilesetAnim_JohtoGeneral

	.align 2
gTileset_JohtoBuilding::
	.byte TRUE @ is compressed
	.byte FALSE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_JohtoBuilding
	.4byte gTilesetPalettes_JohtoBuilding
	.4byte gMetatiles_JohtoBuilding
	.4byte gMetatileAttributes_JohtoBuilding
	.4byte NULL

	.align 2
gTileset_NewBarkTown::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_NewBarkTown
	.4byte gTilesetPalettes_NewBarkTown
	.4byte gMetatiles_NewBarkTown
	.4byte gMetatileAttributes_NewBarkTown
	.4byte NULL

	.align 2
gTileset_JohtoBuilding1::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_JohtoBuilding1
	.4byte gTilesetPalettes_JohtoBuilding1
	.4byte gMetatiles_JohtoBuilding1
	.4byte gMetatileAttributes_JohtoBuilding1
	.4byte NULL

	.align 2
gTileset_VioletCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_VioletCity
	.4byte gTilesetPalettes_VioletCity
	.4byte gMetatiles_VioletCity
	.4byte gMetatileAttributes_VioletCity
	.4byte NULL

	.align 2
gTileset_VioletCityGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_VioletCityGym
	.4byte gTilesetPalettes_VioletCityGym
	.4byte gMetatiles_VioletCityGym
	.4byte gMetatileAttributes_VioletCityGym
	.4byte NULL

	.align 2
gTileset_PagodaTower::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_PagodaTower
	.4byte gTilesetPalettes_PagodaTower
	.4byte gMetatiles_PagodaTower
	.4byte gMetatileAttributes_PagodaTower
	.4byte NULL

	.align 2
gTileset_JohtoCave::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_JohtoCave
	.4byte gTilesetPalettes_JohtoCave
	.4byte gMetatiles_JohtoCave
	.4byte gMetatileAttributes_JohtoCave
	.4byte NULL

	.align 2
gTileset_AzaleaTown::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_AzaleaTown
	.4byte gTilesetPalettes_AzaleaTown
	.4byte gMetatiles_AzaleaTown
	.4byte gMetatileAttributes_AzaleaTown
	.4byte NULL

	.align 2
gTileset_JohtoBikeShop::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_JohtoBikeShop
	.4byte gTilesetPalettes_JohtoBikeShop
	.4byte gMetatiles_JohtoBikeShop
	.4byte gMetatileAttributes_JohtoBikeShop
	.4byte NULL

	.align 2
gTileset_AzaleaGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_AzaleaGym
	.4byte gTilesetPalettes_AzaleaGym
	.4byte gMetatiles_AzaleaGym
	.4byte gMetatileAttributes_AzaleaGym
	.4byte NULL

	.align 2
gTileset_GoldenrodCity::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_GoldenrodCity
	.4byte gTilesetPalettes_GoldenrodCity
	.4byte gMetatiles_GoldenrodCity
	.4byte gMetatileAttributes_GoldenrodCity
	.4byte NULL

	.align 2
gTileset_JohtoForest::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_JohtoForest
	.4byte gTilesetPalettes_JohtoForest
	.4byte gMetatiles_JohtoForest
	.4byte gMetatileAttributes_JohtoForest
	.4byte NULL

	.align 2
gTileset_JohtoDayCare::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_JohtoDayCare
	.4byte gTilesetPalettes_JohtoDayCare
	.4byte gMetatiles_JohtoDayCare
	.4byte gMetatileAttributes_JohtoDayCare
	.4byte NULL

	.align 2
gTileset_JohtoUnderground::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_JohtoUnderground
	.4byte gTilesetPalettes_JohtoUnderground
	.4byte gMetatiles_JohtoUnderground
	.4byte gMetatileAttributes_JohtoUnderground
	.4byte NULL

	.align 2
gTileset_GoldenrodGym::
	.byte TRUE @ is compressed
	.byte TRUE @ is secondary
	.2byte 0
	.4byte gTilesetTiles_GoldenrodGym
	.4byte gTilesetPalettes_GoldenrodGym
	.4byte gMetatiles_GoldenrodGym
	.4byte gMetatileAttributes_GoldenrodGym
	.4byte NULL
