	.align 1
gMetatiles_General::
	.incbin "data/tilesets/primary/general/metatiles.bin"

	.align 1
gMetatileAttributes_General::
	.incbin "data/tilesets/primary/general/metatile_attributes.bin"

	.align 1
gMetatiles_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/metatiles.bin"

	.align 1
gMetatileAttributes_Petalburg::
	.incbin "data/tilesets/secondary/petalburg/metatile_attributes.bin"

	.align 1
gMetatiles_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/metatiles.bin"

	.align 1
gMetatileAttributes_Rustboro::
	.incbin "data/tilesets/secondary/rustboro/metatile_attributes.bin"

	.align 1
gMetatiles_Dewford::
	.incbin "data/tilesets/secondary/dewford/metatiles.bin"

	.align 1
gMetatileAttributes_Dewford::
	.incbin "data/tilesets/secondary/dewford/metatile_attributes.bin"

	.align 1
gMetatiles_Slateport::
	.incbin "data/tilesets/secondary/slateport/metatiles.bin"

	.align 1
gMetatileAttributes_Slateport::
	.incbin "data/tilesets/secondary/slateport/metatile_attributes.bin"

	.align 1
gMetatiles_Mauville::
	.incbin "data/tilesets/secondary/mauville/metatiles.bin"

	.align 1
gMetatileAttributes_Mauville::
	.incbin "data/tilesets/secondary/mauville/metatile_attributes.bin"

	.align 1
gMetatiles_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/metatiles.bin"

	.align 1
gMetatileAttributes_Lavaridge::
	.incbin "data/tilesets/secondary/lavaridge/metatile_attributes.bin"

	.align 1
gMetatiles_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/metatiles.bin"

	.align 1
gMetatileAttributes_Fallarbor::
	.incbin "data/tilesets/secondary/fallarbor/metatile_attributes.bin"

	.align 1
gMetatiles_Fortree::
	.incbin "data/tilesets/secondary/fortree/metatiles.bin"

	.align 1
gMetatileAttributes_Fortree::
	.incbin "data/tilesets/secondary/fortree/metatile_attributes.bin"

	.align 1
gMetatiles_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/metatiles.bin"

	.align 1
gMetatileAttributes_Lilycove::
	.incbin "data/tilesets/secondary/lilycove/metatile_attributes.bin"

	.align 1
gMetatiles_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/metatiles.bin"

	.align 1
gMetatileAttributes_Mossdeep::
	.incbin "data/tilesets/secondary/mossdeep/metatile_attributes.bin"

	.align 1
gMetatiles_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/metatiles.bin"

	.align 1
gMetatileAttributes_EverGrande::
	.incbin "data/tilesets/secondary/ever_grande/metatile_attributes.bin"

	.align 1
gMetatiles_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/metatiles.bin"

	.align 1
gMetatileAttributes_Pacifidlog::
	.incbin "data/tilesets/secondary/pacifidlog/metatile_attributes.bin"

	.align 1
gMetatiles_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/metatiles.bin"

	.align 1
gMetatileAttributes_Sootopolis::
	.incbin "data/tilesets/secondary/sootopolis/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideWest::
	.incbin "data/tilesets/secondary/battle_frontier_outside_west/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierOutsideEast::
	.incbin "data/tilesets/secondary/battle_frontier_outside_east/metatile_attributes.bin"

	.align 1
gMetatiles_InsideBuilding::
	.incbin "data/tilesets/primary/building/metatiles.bin"

	.align 1
gMetatileAttributes_InsideBuilding::
	.incbin "data/tilesets/primary/building/metatile_attributes.bin"

	.align 1
gMetatiles_Shop::
	.incbin "data/tilesets/secondary/shop/metatiles.bin"

	.align 1
gMetatileAttributes_Shop::
	.incbin "data/tilesets/secondary/shop/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonCenter::
	.incbin "data/tilesets/secondary/pokemon_center/metatile_attributes.bin"

	.align 1
gMetatiles_Cave::
	.incbin "data/tilesets/secondary/cave/metatiles.bin"

	.align 1
gMetatileAttributes_Cave::
	.incbin "data/tilesets/secondary/cave/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonSchool::
	.incbin "data/tilesets/secondary/pokemon_school/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonFanClub::
	.incbin "data/tilesets/secondary/pokemon_fan_club/metatile_attributes.bin"

	.align 1
gMetatiles_Unused1::
	.incbin "data/tilesets/secondary/unused_1/metatiles.bin"

	.align 1
gMetatileAttributes_Unused1::
	.incbin "data/tilesets/secondary/unused_1/metatile_attributes.bin"

	.align 1
gMetatiles_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/metatiles.bin"

	.align 1
gMetatileAttributes_MeteorFalls::
	.incbin "data/tilesets/secondary/meteor_falls/metatile_attributes.bin"

	.align 1
gMetatiles_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/metatiles.bin"

	.align 1
gMetatileAttributes_OceanicMuseum::
	.incbin "data/tilesets/secondary/oceanic_museum/metatile_attributes.bin"

	.align 1
gMetatiles_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatiles.bin"

	.align 1
gMetatileAttributes_CableClub::
	.incbin "data/tilesets/secondary/cable_club/metatile_attributes.bin"

	.align 1
gMetatiles_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/metatiles.bin"

	.align 1
gMetatileAttributes_SeashoreHouse::
	.incbin "data/tilesets/secondary/seashore_house/metatile_attributes.bin"

	.align 1
gMetatiles_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/metatiles.bin"

	.align 1
gMetatileAttributes_PrettyPetalFlowerShop::
	.incbin "data/tilesets/secondary/pretty_petal_flower_shop/metatile_attributes.bin"

	.align 1
gMetatiles_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonDayCare::
	.incbin "data/tilesets/secondary/pokemon_day_care/metatile_attributes.bin"

	.align 1
gMetatiles_Facility::
	.incbin "data/tilesets/secondary/facility/metatiles.bin"

	.align 1
gMetatileAttributes_Facility::
	.incbin "data/tilesets/secondary/facility/metatile_attributes.bin"

	.align 1
gMetatiles_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatiles.bin"

	.align 1
gMetatileAttributes_BikeShop::
	.incbin "data/tilesets/secondary/bike_shop/metatile_attributes.bin"

	.align 1
gMetatiles_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/metatiles.bin"

	.align 1
gMetatileAttributes_RusturfTunnel::
	.incbin "data/tilesets/secondary/rusturf_tunnel/metatile_attributes.bin"

	.align 1
gMetatiles_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBaseSecondary::
	.incbin "data/tilesets/secondary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/metatiles.bin"

	.align 1
gMetatileAttributes_InsideOfTruck::
	.incbin "data/tilesets/secondary/inside_of_truck/metatile_attributes.bin"

	.align 1
gMetatiles_Contest::
	.incbin "data/tilesets/secondary/contest/metatiles.bin"

	.align 1
gMetatileAttributes_Contest::
	.incbin "data/tilesets/secondary/contest/metatile_attributes.bin"

	.align 1
gMetatiles_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/metatiles.bin"

	.align 1
gMetatileAttributes_LilycoveMuseum::
	.incbin "data/tilesets/secondary/lilycove_museum/metatile_attributes.bin"

	.align 1
gMetatiles_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/metatiles.bin"

	.align 1
gMetatileAttributes_BrendansMaysHouse::
	.incbin "data/tilesets/secondary/brendans_mays_house/metatile_attributes.bin"

	.align 1
gMetatiles_Lab::
	.incbin "data/tilesets/secondary/lab/metatiles.bin"

	.align 1
gMetatileAttributes_Lab::
	.incbin "data/tilesets/secondary/lab/metatile_attributes.bin"

	.align 1
gMetatiles_Underwater::
	.incbin "data/tilesets/secondary/underwater/metatiles.bin"

	.align 1
gMetatileAttributes_Underwater::
	.incbin "data/tilesets/secondary/underwater/metatile_attributes.bin"

	.align 1
gMetatiles_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/metatiles.bin"

	.align 1
gMetatileAttributes_GenericBuilding::
	.incbin "data/tilesets/secondary/generic_building/metatile_attributes.bin"

	.align 1
gMetatiles_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_MauvilleGameCorner::
	.incbin "data/tilesets/secondary/mauville_game_corner/metatile_attributes.bin"

	.align 1
gMetatiles_Unused2::
	.incbin "data/tilesets/secondary/unused_2/metatiles.bin"

	.align 1
gMetatileAttributes_Unused2::
	.incbin "data/tilesets/secondary/unused_2/metatile_attributes.bin"

	.align 1
gMetatiles_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/metatiles.bin"

	.align 1
gMetatileAttributes_RustboroGym::
	.incbin "data/tilesets/secondary/rustboro_gym/metatile_attributes.bin"

	.align 1
gMetatiles_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/metatiles.bin"

	.align 1
gMetatileAttributes_DewfordGym::
	.incbin "data/tilesets/secondary/dewford_gym/metatile_attributes.bin"

	.align 1
gMetatiles_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/metatiles.bin"

	.align 1
gMetatileAttributes_MauvilleGym::
	.incbin "data/tilesets/secondary/mauville_gym/metatile_attributes.bin"

	.align 1
gMetatiles_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/metatiles.bin"

	.align 1
gMetatileAttributes_LavaridgeGym::
	.incbin "data/tilesets/secondary/lavaridge_gym/metatile_attributes.bin"

	.align 1
gMetatiles_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/metatiles.bin"

	.align 1
gMetatileAttributes_PetalburgGym::
	.incbin "data/tilesets/secondary/petalburg_gym/metatile_attributes.bin"

	.align 1
gMetatiles_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/metatiles.bin"

	.align 1
gMetatileAttributes_FortreeGym::
	.incbin "data/tilesets/secondary/fortree_gym/metatile_attributes.bin"

	.align 1
gMetatiles_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/metatiles.bin"

	.align 1
gMetatileAttributes_MossdeepGym::
	.incbin "data/tilesets/secondary/mossdeep_gym/metatile_attributes.bin"

	.align 1
gMetatiles_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/metatiles.bin"

	.align 1
gMetatileAttributes_SootopolisGym::
	.incbin "data/tilesets/secondary/sootopolis_gym/metatile_attributes.bin"

	.align 1
gMetatiles_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatiles.bin"

	.align 1
gMetatileAttributes_TrickHousePuzzle::
	.incbin "data/tilesets/secondary/trick_house_puzzle/metatile_attributes.bin"

	.align 1
gMetatiles_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/metatiles.bin"

	.align 1
gMetatileAttributes_InsideShip::
	.incbin "data/tilesets/secondary/inside_ship/metatile_attributes.bin"

	.align 1
gMetatiles_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatiles.bin"

	.align 1
gMetatileAttributes_SecretBasePrimary::
	.incbin "data/tilesets/primary/secret_base/metatile_attributes.bin"

	.align 1
gMetatiles_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/metatiles.bin"

	.align 1
gMetatileAttributes_EliteFour::
	.incbin "data/tilesets/secondary/elite_four/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontier::
	.incbin "data/tilesets/secondary/battle_frontier/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePalace::
	.incbin "data/tilesets/secondary/battle_palace/metatile_attributes.bin"

	.align 1
gMetatiles_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/metatiles.bin"

	.align 1
gMetatileAttributes_BattleDome::
	.incbin "data/tilesets/secondary/battle_dome/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFactory::
	.incbin "data/tilesets/secondary/battle_factory/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePike::
	.incbin "data/tilesets/secondary/battle_pike/metatile_attributes.bin"

	.align 1
gMetatiles_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/metatiles.bin"

	.align 1
gMetatileAttributes_BattleArena::
	.incbin "data/tilesets/secondary/battle_arena/metatile_attributes.bin"

	.align 1
gMetatiles_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/metatiles.bin"

	.align 1
gMetatileAttributes_BattlePyramid::
	.incbin "data/tilesets/secondary/battle_pyramid/metatile_attributes.bin"

	.align 1
gMetatiles_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/metatiles.bin"

	.align 1
gMetatileAttributes_MirageTower::
	.incbin "data/tilesets/secondary/mirage_tower/metatile_attributes.bin"

	.align 1
gMetatiles_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatiles.bin"

	.align 1
gMetatileAttributes_MossdeepGameCorner::
	.incbin "data/tilesets/secondary/mossdeep_game_corner/metatile_attributes.bin"

	.align 1
gMetatiles_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatiles.bin"

	.align 1
gMetatileAttributes_IslandHarbor::
	.incbin "data/tilesets/secondary/island_harbor/metatile_attributes.bin"

	.align 1
gMetatiles_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/metatiles.bin"

	.align 1
gMetatileAttributes_TrainerHill::
	.incbin "data/tilesets/secondary/trainer_hill/metatile_attributes.bin"

	.align 1
gMetatiles_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatiles.bin"

	.align 1
gMetatileAttributes_NavelRock::
	.incbin "data/tilesets/secondary/navel_rock/metatile_attributes.bin"

	.align 1
gMetatiles_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatiles.bin"

	.align 1
gMetatileAttributes_BattleFrontierRankingHall::
	.incbin "data/tilesets/secondary/battle_frontier_ranking_hall/metatile_attributes.bin"

	.align 1
gMetatiles_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/metatiles.bin"

	.align 1
gMetatileAttributes_BattleTent::
	.incbin "data/tilesets/secondary/battle_tent/metatile_attributes.bin"

	.align 1
gMetatiles_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/metatiles.bin"

	.align 1
gMetatileAttributes_MysteryEventsHouse::
	.incbin "data/tilesets/secondary/mystery_events_house/metatile_attributes.bin"

	.align 1
gMetatiles_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/metatiles.bin"

	.align 1
gMetatileAttributes_UnionRoom::
	.incbin "data/tilesets/secondary/union_room/metatile_attributes.bin"

	.align 1
gMetatiles_KantoGeneral::
	.incbin "data/tilesets/primary/kantogeneral/metatiles.bin"

	.align 1
gMetatileAttributes_KantoGeneral::
	.incbin "data/tilesets/primary/kantogeneral/metatile_attributes.bin"
	.align 1
gMetatiles_PalletTown::
	.incbin "data/tilesets/secondary/pallettown/metatiles.bin"

	.align 1
gMetatileAttributes_PalletTown::
	.incbin "data/tilesets/secondary/pallettown/metatile_attributes.bin"
	.align 1
gMetatiles_ViridianCity::
	.incbin "data/tilesets/secondary/viridiancity/metatiles.bin"

	.align 1
gMetatileAttributes_ViridianCity::
	.incbin "data/tilesets/secondary/viridiancity/metatile_attributes.bin"
	.align 1
gMetatiles_KantoBuilding::
	.incbin "data/tilesets/primary/kantobuilding/metatiles.bin"

	.align 1
gMetatileAttributes_KantoBuilding::
	.incbin "data/tilesets/primary/kantobuilding/metatile_attributes.bin"
	.align 1
gMetatiles_KantoBuilding1::
	.incbin "data/tilesets/secondary/kantobuilding1/metatiles.bin"

	.align 1
gMetatileAttributes_KantoBuilding1::
	.incbin "data/tilesets/secondary/kantobuilding1/metatile_attributes.bin"
	.align 1
gMetatiles_KantoBuilding2::
	.incbin "data/tilesets/secondary/kantobuilding2/metatiles.bin"

	.align 1
gMetatileAttributes_KantoBuilding2::
	.incbin "data/tilesets/secondary/kantobuilding2/metatile_attributes.bin"
	.align 1
gMetatiles_KantoOaksLab::
	.incbin "data/tilesets/secondary/kantooakslab/metatiles.bin"

	.align 1
gMetatileAttributes_KantoOaksLab::
	.incbin "data/tilesets/secondary/kantooakslab/metatile_attributes.bin"
	.align 1
gMetatiles_ViridianCityGym::
	.incbin "data/tilesets/secondary/viridiancitygym/metatiles.bin"

	.align 1
gMetatileAttributes_ViridianCityGym::
	.incbin "data/tilesets/secondary/viridiancitygym/metatile_attributes.bin"
	.align 1
gMetatiles_KantoBuilding3::
	.incbin "data/tilesets/secondary/kantobuilding3/metatiles.bin"

	.align 1
gMetatileAttributes_KantoBuilding3::
	.incbin "data/tilesets/secondary/kantobuilding3/metatile_attributes.bin"
	.align 1
gMetatiles_KantoPokeMart::
	.incbin "data/tilesets/secondary/kantopokemart/metatiles.bin"

	.align 1
gMetatileAttributes_KantoPokeMart::
	.incbin "data/tilesets/secondary/kantopokemart/metatile_attributes.bin"
	.align 1
gMetatiles_KantoPokeCenter::
	.incbin "data/tilesets/secondary/kantopokecenter/metatiles.bin"

	.align 1
gMetatileAttributes_KantoPokeCenter::
	.incbin "data/tilesets/secondary/kantopokecenter/metatile_attributes.bin"
	.align 1
gMetatiles_PewterCity::
	.incbin "data/tilesets/secondary/pewtercity/metatiles.bin"

	.align 1
gMetatileAttributes_PewterCity::
	.incbin "data/tilesets/secondary/pewtercity/metatile_attributes.bin"
	.align 1
gMetatiles_PewterCityMuseum::
	.incbin "data/tilesets/secondary/pewtercitymuseum/metatiles.bin"

	.align 1
gMetatileAttributes_PewterCityMuseum::
	.incbin "data/tilesets/secondary/pewtercitymuseum/metatile_attributes.bin"
	.align 1
gMetatiles_PewterCityGym::
	.incbin "data/tilesets/secondary/pewtercitygym/metatiles.bin"

	.align 1
gMetatileAttributes_PewterCityGym::
	.incbin "data/tilesets/secondary/pewtercitygym/metatile_attributes.bin"
	.align 1
gMetatiles_CeruleanCity::
	.incbin "data/tilesets/secondary/ceruleancity/metatiles.bin"

	.align 1
gMetatileAttributes_CeruleanCity::
	.incbin "data/tilesets/secondary/ceruleancity/metatile_attributes.bin"
	.align 1
gMetatiles_CeruleanCityCrimeHouse::
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/metatiles.bin"

	.align 1
gMetatileAttributes_CeruleanCityCrimeHouse::
	.incbin "data/tilesets/secondary/ceruleancitycrimehouse/metatile_attributes.bin"
	.align 1
gMetatiles_CeruleanCityGym::
	.incbin "data/tilesets/secondary/ceruleancitygym/metatiles.bin"

	.align 1
gMetatileAttributes_CeruleanCityGym::
	.incbin "data/tilesets/secondary/ceruleancitygym/metatile_attributes.bin"
	.align 1
gMetatiles_CeruleanCityBikeShop::
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/metatiles.bin"

	.align 1
gMetatileAttributes_CeruleanCityBikeShop::
	.incbin "data/tilesets/secondary/ceruleancitybikeshop/metatile_attributes.bin"
	.align 1
gMetatiles_LavenderTown::
	.incbin "data/tilesets/secondary/lavendertown/metatiles.bin"

	.align 1
gMetatileAttributes_LavenderTown::
	.incbin "data/tilesets/secondary/lavendertown/metatile_attributes.bin"
	.align 1
gMetatiles_KantoDayCare::
	.incbin "data/tilesets/secondary/kantodaycare/metatiles.bin"

	.align 1
gMetatileAttributes_KantoDayCare::
	.incbin "data/tilesets/secondary/kantodaycare/metatile_attributes.bin"
	.align 1
gMetatiles_PokemonTower::
	.incbin "data/tilesets/secondary/pokemontower/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonTower::
	.incbin "data/tilesets/secondary/pokemontower/metatile_attributes.bin"
	.align 1
gMetatiles_VermilionCity::
	.incbin "data/tilesets/secondary/vermilioncity/metatiles.bin"

	.align 1
gMetatileAttributes_VermilionCity::
	.incbin "data/tilesets/secondary/vermilioncity/metatile_attributes.bin"
	.align 1
gMetatiles_VermilionCityGym::
	.incbin "data/tilesets/secondary/vermilioncitygym/metatiles.bin"

	.align 1
gMetatileAttributes_VermilionCityGym::
	.incbin "data/tilesets/secondary/vermilioncitygym/metatile_attributes.bin"
	.align 1
gMetatiles_CeladonCity::
	.incbin "data/tilesets/secondary/celadoncity/metatiles.bin"

	.align 1
gMetatileAttributes_CeladonCity::
	.incbin "data/tilesets/secondary/celadoncity/metatile_attributes.bin"
	.align 1
gMetatiles_CeladonDepartmentStore::
	.incbin "data/tilesets/secondary/celadondepartmentstore/metatiles.bin"

	.align 1
gMetatileAttributes_CeladonDepartmentStore::
	.incbin "data/tilesets/secondary/celadondepartmentstore/metatile_attributes.bin"
	.align 1
gMetatiles_SilphCo::
	.incbin "data/tilesets/secondary/silphco/metatiles.bin"

	.align 1
gMetatileAttributes_SilphCo::
	.incbin "data/tilesets/secondary/silphco/metatile_attributes.bin"
	.align 1
gMetatiles_Condominiums::
	.incbin "data/tilesets/secondary/condominiums/metatiles.bin"

	.align 1
gMetatileAttributes_Condominiums::
	.incbin "data/tilesets/secondary/condominiums/metatile_attributes.bin"
	.align 1
gMetatiles_GameCorner::
	.incbin "data/tilesets/secondary/gamecorner/metatiles.bin"

	.align 1
gMetatileAttributes_GameCorner::
	.incbin "data/tilesets/secondary/gamecorner/metatile_attributes.bin"
	.align 1
gMetatiles_CeladonCityGym::
	.incbin "data/tilesets/secondary/celadoncitygym/metatiles.bin"

	.align 1
gMetatileAttributes_CeladonCityGym::
	.incbin "data/tilesets/secondary/celadoncitygym/metatile_attributes.bin"
	.align 1
gMetatiles_CeladonHotel::
	.incbin "data/tilesets/secondary/celadonhotel/metatiles.bin"

	.align 1
gMetatileAttributes_CeladonHotel::
	.incbin "data/tilesets/secondary/celadonhotel/metatile_attributes.bin"
	.align 1
gMetatiles_FuchsiaCity::
	.incbin "data/tilesets/secondary/fuchsiacity/metatiles.bin"

	.align 1
gMetatileAttributes_FuchsiaCity::
	.incbin "data/tilesets/secondary/fuchsiacity/metatile_attributes.bin"
	.align 1
gMetatiles_KantoSafariBuilding::
	.incbin "data/tilesets/secondary/kantosafaribuilding/metatiles.bin"

	.align 1
gMetatileAttributes_KantoSafariBuilding::
	.incbin "data/tilesets/secondary/kantosafaribuilding/metatile_attributes.bin"
	.align 1
gMetatiles_FuchsiaCityGym::
	.incbin "data/tilesets/secondary/fuchsiacitygym/metatiles.bin"

	.align 1
gMetatileAttributes_FuchsiaCityGym::
	.incbin "data/tilesets/secondary/fuchsiacitygym/metatile_attributes.bin"
	.align 1
gMetatiles_CinnabarIsland::
	.incbin "data/tilesets/secondary/cinnabarisland/metatiles.bin"

	.align 1
gMetatileAttributes_CinnabarIsland::
	.incbin "data/tilesets/secondary/cinnabarisland/metatile_attributes.bin"
	.align 1
gMetatiles_CinnabarIslandGym::
	.incbin "data/tilesets/secondary/cinnabarislandgym/metatiles.bin"

	.align 1
gMetatileAttributes_CinnabarIslandGym::
	.incbin "data/tilesets/secondary/cinnabarislandgym/metatile_attributes.bin"
	.align 1
gMetatiles_PokemonMansion::
	.incbin "data/tilesets/secondary/pokemonmansion/metatiles.bin"

	.align 1
gMetatileAttributes_PokemonMansion::
	.incbin "data/tilesets/secondary/pokemonmansion/metatile_attributes.bin"
	.align 1
gMetatiles_SaffronCity::
	.incbin "data/tilesets/secondary/saffroncity/metatiles.bin"

	.align 1
gMetatileAttributes_SaffronCity::
	.incbin "data/tilesets/secondary/saffroncity/metatile_attributes.bin"
	.align 1
gMetatiles_SaffronCityGym::
	.incbin "data/tilesets/secondary/saffroncitygym/metatiles.bin"

	.align 1
gMetatileAttributes_SaffronCityGym::
	.incbin "data/tilesets/secondary/saffroncitygym/metatile_attributes.bin"
	.align 1
gMetatiles_IndigoPlateau::
	.incbin "data/tilesets/secondary/indigoplateau/metatiles.bin"

	.align 1
gMetatileAttributes_IndigoPlateau::
	.incbin "data/tilesets/secondary/indigoplateau/metatile_attributes.bin"
	.align 1
gMetatiles_KantoPokemonLeague::
	.incbin "data/tilesets/secondary/kantopokemonleague/metatiles.bin"

	.align 1
gMetatileAttributes_KantoPokemonLeague::
	.incbin "data/tilesets/secondary/kantopokemonleague/metatile_attributes.bin"
	.align 1
gMetatiles_KantoHallOfFame::
	.incbin "data/tilesets/secondary/kantohalloffame/metatiles.bin"

	.align 1
gMetatileAttributes_KantoHallOfFame::
	.incbin "data/tilesets/secondary/kantohalloffame/metatile_attributes.bin"
	.align 1
gMetatiles_ViridianForest::
	.incbin "data/tilesets/secondary/viridianforest/metatiles.bin"

	.align 1
gMetatileAttributes_ViridianForest::
	.incbin "data/tilesets/secondary/viridianforest/metatile_attributes.bin"
	.align 1
gMetatiles_DiglettsCave::
	.incbin "data/tilesets/secondary/diglettscave/metatiles.bin"

	.align 1
gMetatileAttributes_DiglettsCave::
	.incbin "data/tilesets/secondary/diglettscave/metatile_attributes.bin"
	.align 1
gMetatiles_MtMoon::
	.incbin "data/tilesets/secondary/mtmoon/metatiles.bin"

	.align 1
gMetatileAttributes_MtMoon::
	.incbin "data/tilesets/secondary/mtmoon/metatile_attributes.bin"
	.align 1
gMetatiles_UndergroundPass::
	.incbin "data/tilesets/secondary/undergroundpass/metatiles.bin"

	.align 1
gMetatileAttributes_UndergroundPass::
	.incbin "data/tilesets/secondary/undergroundpass/metatile_attributes.bin"
	.align 1
gMetatiles_RockTunnel::
	.incbin "data/tilesets/secondary/rocktunnel/metatiles.bin"

	.align 1
gMetatileAttributes_RockTunnel::
	.incbin "data/tilesets/secondary/rocktunnel/metatile_attributes.bin"
	.align 1
gMetatiles_KantoPowerPlant::
	.incbin "data/tilesets/secondary/kantopowerplant/metatiles.bin"

	.align 1
gMetatileAttributes_KantoPowerPlant::
	.incbin "data/tilesets/secondary/kantopowerplant/metatile_attributes.bin"
	.align 1
gMetatiles_SeafoamIslands::
	.incbin "data/tilesets/secondary/seafoamislands/metatiles.bin"

	.align 1
gMetatileAttributes_SeafoamIslands::
	.incbin "data/tilesets/secondary/seafoamislands/metatile_attributes.bin"
	.align 1
gMetatiles_SeaCottage::
	.incbin "data/tilesets/secondary/seacottage/metatiles.bin"

	.align 1
gMetatileAttributes_SeaCottage::
	.incbin "data/tilesets/secondary/seacottage/metatile_attributes.bin"
	.align 1
gMetatiles_CeruleanCave::
	.incbin "data/tilesets/secondary/ceruleancave/metatiles.bin"

	.align 1
gMetatileAttributes_CeruleanCave::
	.incbin "data/tilesets/secondary/ceruleancave/metatile_attributes.bin"
	.align 1
gMetatiles_SeviiIsles1::
	.incbin "data/tilesets/secondary/seviiisles1/metatiles.bin"

	.align 1
gMetatileAttributes_SeviiIsles1::
	.incbin "data/tilesets/secondary/seviiisles1/metatile_attributes.bin"
	.align 1
gMetatiles_KantoHarbor::
	.incbin "data/tilesets/secondary/kantoharbor/metatiles.bin"

	.align 1
gMetatileAttributes_KantoHarbor::
	.incbin "data/tilesets/secondary/kantoharbor/metatile_attributes.bin"
	.align 1
gMetatiles_MtEmber::
	.incbin "data/tilesets/secondary/mtember/metatiles.bin"

	.align 1
gMetatileAttributes_MtEmber::
	.incbin "data/tilesets/secondary/mtember/metatile_attributes.bin"
	.align 1
gMetatiles_BerryForest::
	.incbin "data/tilesets/secondary/berryforest/metatiles.bin"

	.align 1
gMetatileAttributes_BerryForest::
	.incbin "data/tilesets/secondary/berryforest/metatile_attributes.bin"
	.align 1
gMetatiles_SeviiIsles2::
	.incbin "data/tilesets/secondary/seviiisles2/metatiles.bin"

	.align 1
gMetatileAttributes_SeviiIsles2::
	.incbin "data/tilesets/secondary/seviiisles2/metatile_attributes.bin"
	.align 1
gMetatiles_SeviiIsles3::
	.incbin "data/tilesets/secondary/seviiisles3/metatiles.bin"

	.align 1
gMetatileAttributes_SeviiIsles3::
	.incbin "data/tilesets/secondary/seviiisles3/metatile_attributes.bin"
	.align 1
gMetatiles_DottedHole::
	.incbin "data/tilesets/secondary/dottedhole/metatiles.bin"

	.align 1
gMetatileAttributes_DottedHole::
	.incbin "data/tilesets/secondary/dottedhole/metatile_attributes.bin"
	.align 1
gMetatiles_TanobyRuins::
	.incbin "data/tilesets/secondary/tanobyruins/metatiles.bin"

	.align 1
gMetatileAttributes_TanobyRuins::
	.incbin "data/tilesets/secondary/tanobyruins/metatile_attributes.bin"
	.align 1
gMetatiles_KantoTrainerTower::
	.incbin "data/tilesets/secondary/kantotrainertower/metatiles.bin"

	.align 1
gMetatileAttributes_KantoTrainerTower::
	.incbin "data/tilesets/secondary/kantotrainertower/metatile_attributes.bin"

	.align 1
gMetatiles_JohtoGeneral::
	.incbin "data/tilesets/primary/johtogeneral/metatiles.bin"

	.align 1
gMetatileAttributes_JohtoGeneral::
	.incbin "data/tilesets/primary/johtogeneral/metatile_attributes.bin"
	.align 1
gMetatiles_JohtoBuilding::
	.incbin "data/tilesets/primary/johtobuilding/metatiles.bin"

	.align 1
gMetatileAttributes_JohtoBuilding::
	.incbin "data/tilesets/primary/johtobuilding/metatile_attributes.bin"
	.align 1

gMetatiles_NewBarkTown::
	.incbin "data/tilesets/secondary/newbarktown/metatiles.bin"

	.align 1
gMetatileAttributes_NewBarkTown::
	.incbin "data/tilesets/secondary/newbarktown/metatile_attributes.bin"

	.align 1
gMetatiles_JohtoBuilding1::
	.incbin "data/tilesets/secondary/johtobuilding1/metatiles.bin"

	.align 1
gMetatileAttributes_JohtoBuilding1::
	.incbin "data/tilesets/secondary/johtobuilding1/metatile_attributes.bin"
	.align 1
gMetatiles_VioletCity::
	.incbin "data/tilesets/secondary/violetcity/metatiles.bin"

	.align 1
gMetatileAttributes_VioletCity::
	.incbin "data/tilesets/secondary/violetcity/metatile_attributes.bin"
	.align 1
gMetatiles_VioletCityGym::
	.incbin "data/tilesets/secondary/violetcitygym/metatiles.bin"

	.align 1
gMetatileAttributes_VioletCityGym::
	.incbin "data/tilesets/secondary/violetcitygym/metatile_attributes.bin"
	.align 1
gMetatiles_PagodaTower::
	.incbin "data/tilesets/secondary/pagodatower/metatiles.bin"

	.align 1
gMetatileAttributes_PagodaTower::
	.incbin "data/tilesets/secondary/pagodatower/metatile_attributes.bin"
	.align 1
gMetatiles_JohtoCave::
	.incbin "data/tilesets/secondary/johtocave/metatiles.bin"

	.align 1
gMetatileAttributes_JohtoCave::
	.incbin "data/tilesets/secondary/johtocave/metatile_attributes.bin"
	.align 1
gMetatiles_AzaleaTown::
	.incbin "data/tilesets/secondary/azaleatown/metatiles.bin"

	.align 1
gMetatileAttributes_AzaleaTown::
	.incbin "data/tilesets/secondary/azaleatown/metatile_attributes.bin"
	.align 1
gMetatiles_JohtoBikeShop::
	.incbin "data/tilesets/secondary/johtobikeshop/metatiles.bin"

	.align 1
gMetatileAttributes_JohtoBikeShop::
	.incbin "data/tilesets/secondary/johtobikeshop/metatile_attributes.bin"
	.align 1
gMetatiles_AzaleaGym::
	.incbin "data/tilesets/secondary/azaleagym/metatiles.bin"

	.align 1
gMetatileAttributes_AzaleaGym::
	.incbin "data/tilesets/secondary/azaleagym/metatile_attributes.bin"
	.align 1
gMetatiles_GoldenrodCity::
	.incbin "data/tilesets/secondary/goldenrodcity/metatiles.bin"

	.align 1
gMetatileAttributes_GoldenrodCity::
	.incbin "data/tilesets/secondary/goldenrodcity/metatile_attributes.bin"
	.align 1
gMetatiles_JohtoForest::
	.incbin "data/tilesets/secondary/johtoforest/metatiles.bin"

	.align 1
gMetatileAttributes_JohtoForest::
	.incbin "data/tilesets/secondary/johtoforest/metatile_attributes.bin"
	.align 1
gMetatiles_JohtoDayCare::
	.incbin "data/tilesets/secondary/johtodaycare/metatiles.bin"

	.align 1
gMetatileAttributes_JohtoDayCare::
	.incbin "data/tilesets/secondary/johtodaycare/metatile_attributes.bin"
	.align 1
gMetatiles_JohtoUnderground::
	.incbin "data/tilesets/secondary/johtounderground/metatiles.bin"

	.align 1
gMetatileAttributes_JohtoUnderground::
	.incbin "data/tilesets/secondary/johtounderground/metatile_attributes.bin"
	.align 1
gMetatiles_GoldenrodGym::
	.incbin "data/tilesets/secondary/goldenrodgym/metatiles.bin"

	.align 1
gMetatileAttributes_GoldenrodGym::
	.incbin "data/tilesets/secondary/goldenrodgym/metatile_attributes.bin"
	.align 1
gMetatiles_NationalPark::
	.incbin "data/tilesets/secondary/nationalpark/metatiles.bin"

	.align 1
gMetatileAttributes_NationalPark::
	.incbin "data/tilesets/secondary/nationalpark/metatile_attributes.bin"
	.align 1
gMetatiles_RuinsOfAlph::
	.incbin "data/tilesets/secondary/ruinsofalph/metatiles.bin"

	.align 1
gMetatileAttributes_RuinsOfAlph::
	.incbin "data/tilesets/secondary/ruinsofalph/metatile_attributes.bin"
